# -*- coding: utf-8 -*-
# Each phase has weeks, each week has 7 days, each day has 3-4 tasks

CURRICULUM = {
    0: [  # Phase 0 — 16 weeks = 56 days — Noi Kinh Nen Tang
        # Week 1
        ['Đọc Tố Vấn Chương 1: Thuong Co Thien Chan Luan', 'Ghi chú 3 khái niệm Âm Dương'],
        ['Đọc Tố Vấn Chương 2: Tu Khi Dieu Than Luan', 'Vẽ sơ đồ 4 mùa ↔ Tang Phu'],
        ['Đọc Tố Vấn Chương 3: Sinh Khi Thong Thien Luan', 'Ghi chú về Dương Khí và bệnh lý'],
        ['Đọc Tố Vấn Chương 4: Kim Quy Chan Ngon Luan', 'Học thuộc Ngũ Hành tương sinh'],
        ['Đọc Tố Vấn Chương 5: Am Duong Ung Tuong Dai Luan (phan 1)', 'Ghi chú 5 âm 5 vị 5 sắc'],
        ['Đọc Tố Vấn Chương 5: Am Duong Ung Tuong Dai Luan (phan 2)', 'Vẽ bảng Ngũ Hành đầy đủ'],
        ['Ôn lại tuần 1 — Tố Vấn Chương 1-5', 'Trả lời: Dương Khí có vai trò gì trong bảo vệ cơ thể?'],
        # Week 2
        ['Đọc Tố Vấn Chương 6: Am Duong Ly Hop Luan', 'Ghi chú 3 âm 3 dương kinh'],
        ['Đọc Tố Vấn Chương 8: Linh Lan Bi Dien Luan — Tang Phu chuc nang', 'Thuoc chuc nang 5 tang'],
        ['Đọc Tố Vấn Chương 9: Luc Tiet Tang Tuong Luan', 'Ghi chú Tạng Tượng học'],
        ['Đọc Tố Vấn Chương 10: Ngu Tang Sinh Thanh', 'Ve so do Ngu Tang quan he'],
        ['Đọc Tố Vấn Chương 11: Ngu Tang Biet Luan', 'Phân biệt Tạng vs Phủ chức năng'],
        ['Bat dau Linh Khu Chuong 1: Cuu Cham Thap Nhi Nguyen', 'Ghi chú 12 huyệt Nguyên'],
        ['Ôn lại tuần 2 — Tạng Phủ chức năng', 'Trả lời: Sự khác nhau giữa Tạng và Phủ?'],
        # Week 3
        ['Đọc Linh Khu Chương 8: Ban Than', 'Ghi chú Thần/Hồn/Phách/Ý/Chí'],
        ['Đọc Linh Khu Chương 10: Kinh Mach — Kinh Thu Thai Am Phe', 'Ve duong kinh Phe'],
        ['Đọc Linh Khu Chương 10 — Kinh Thu Duong Minh Dai Truong', 'Ve duong kinh Dai Truong'],
        ['Đọc Linh Khu Chương 10 — Kinh Tuc Duong Minh Vi + Tuc Thai Am Ty', 'Ve 2 duong kinh'],
        ['Đọc Linh Khu Chương 10 — Kinh Thu Thieu Am Tam + Thu Thai Duong Tieu Truong', 'Ve 2 duong kinh'],
        ['Đọc Linh Khu Chương 10 — Kinh Tuc Thai Duong Bang Quang + Tuc Thieu Am Than', 'Ve 2 duong kinh'],
        ['Ôn 6 kinh đầu — vẽ lại từ trí nhớ', 'Trả lời: Kinh nào đi qua mặt?'],
        # Week 4
        ['Đọc Linh Khu Chương 10 — Kinh Thu Quyet Am Tam Bao + Thu Thieu Duong Tam Tieu', 'Ve 2 duong kinh'],
        ['Đọc Linh Khu Chương 10 — Kinh Tuc Thieu Duong Dom + Tuc Quyet Am Can', 'Ve 2 duong kinh'],
        ['Đọc Linh Khu Chương 10 — Mach Doc + Mach Nham', 'Ve 2 mach ky'],
        ['Đọc Bát Thập Nhất Nan Kinh: Nan 1-10 (mach hoc)', 'Ghi chú: mach binh thuong la gi?'],
        ['Đọc Nan Kinh: Nan 11-22 (mach benh ly)', 'Ghi chú 5 loại mạch chết'],
        ['Đọc Nan Kinh: Nan 23-29 (kinh mach)', 'So sánh với Linh Khu Chuong 10'],
        ['Ôn lại tuần 4 — 12 kinh + Nan Kinh', 'Vẽ vòng lưu chú 12 kinh từ trí nhớ'],
        # Week 5
        ['Đọc Y Học Tam Tự Kinh: Phan Y Hoc Nguyen Luu', 'Ghi chú lịch sử y học từ Thần Nông đến Trương Trọng Cảnh'],
        ['Đọc Y Học Tam Tự Kinh: Phan Am Duong', 'So sánh với Nội Kinh đã học'],
        ['Đọc Y Học Tam Tự Kinh: Phan Tang Phu', 'Kiểm tra lại kiến thức tạng phủ'],
        ['Đọc Y Học Tam Tự Kinh: Phan Kinh Lac', 'So sánh với Linh Khu'],
        ['Đọc Tố Vấn Chương 17: Mach Yeu Tinh Vi Luan', 'Ghi chú tu mua mach tuong'],
        ['Đọc Tố Vấn Chương 18: Binh Nhan Khi Tuong Luan', 'Học mạch bình thường theo mùa'],
        ['Ôn tuần 5 — Y Học Tam Tự Kinh + mạch theo mùa', 'Trả lời: Mạch mùa xuân đặc điểm gì?'],
        # Week 6
        ['Đọc Tố Vấn Chương 19: Ngoc Co Chan Tang Luan — mach chan tang', 'Ghi chú 5 mạch chân tạng'],
        ['Đọc Nan Kinh: Nan 30-47 (Tang Phu chuyen sau)', 'Ghi chú điểm khác vs Nội Kinh'],
        ['Đọc Nan Kinh: Nan 48-61 (benh ly)', 'Ghi chú phân biệt hư/thực'],
        ['Đọc Nan Kinh: Nan 62-68 (huyet dac biet)', 'Ghi chú Ngũ du huyệt lý luận'],
        ['Đọc Nan Kinh: Nan 69-81 (tri tac)', 'Ghi chú nguyên tắc bổ tả'],
        ['Ôn Nan Kinh toàn bộ', 'Tóm tắt 10 điểm quan trọng nhất'],
        ['Nghi on tap — khong doc sach moi', 'Viet lai tu tri nho: 5 chuc nang Tang Phe'],
        # Week 7
        ['Ôn tổng hợp: Âm Dương Ngũ Hành', 'Trả lời 10 câu hỏi tự đặt'],
        ['Ôn tổng hợp: Tạng Phủ chức năng', 'Ve bang Tang-Phu-Kinh-Sac-Vi-Am'],
        ['Ôn tổng hợp: 12 Kinh chính + Kỳ Kinh', 'Vẽ vòng lưu chú từ trí nhớ'],
        ['Ôn tổng hợp: Khí Huyết Tân Dịch', 'Giai thich Nguyen Khi/Tong Khi/Dinh Khi/Ve Khi'],
        ['Ôn tổng hợp: Nan Kinh điểm đặc thù', 'So sanh 5 diem Nan Kinh khac Noi Kinh'],
        ['Đọc lại Nội Kinh Tố Vấn Chương 1 — nhin voi con mat moi', 'Ghi nhan thay doi trong hieu biet'],
        ['Chuẩn bị thi Phase 0 — ôn 160 câu trắc nghiệm', 'Tu hoi 20 cau ngau nhien'],
        # Week 8
        ['Ôn thi: Âm Dương (25 câu đầu)', 'Ghi chú diem yeu'],
        ['Ôn thi: Ngũ Hành (25 câu)', 'Ghi chú diem yeu'],
        ['Ôn thi: Ngũ Tạng (30 câu)', 'Ghi chú diem yeu'],
        ['Ôn thi: Lục Phủ + Khí Huyết (40 câu)', 'Ghi chú diem yeu'],
        ['Ôn thi: Kinh Lạc + Nan Kinh (40 câu)', 'Ghi chú diem yeu'],
        ['Ôn tổng lực — làm lại tất cả điểm yếu', 'Nghi som, ngu du giac'],
        ['Ngày thi Phase 0 — bot sẽ gửi đề thi hôm nay', 'Giu tam binh tinh'],
    ],

    1: [  # Phase 1 — 12 weeks = 84 days — Mach Hoc
        # Week 1 — 6 mach co ban
        ["Đọc Mạch Kinh Quyển 1: Mach hinh 24 loai — Tong quan", "Học mạch Phù — cảm giác nhẹ nổi trên mặt da", "Bắt mạch 20 phút, tìm mạch Phù"],
        ["Đọc Mạch Kinh: Mach Tram — cam giac nang sau", "So sánh Phù vs Trầm trên cùng người", "Bắt mạch người thân"],
        ["Đọc Mạch Kinh: Mach Tri (cham <4 nhip/ho hap)", "Đếm nhịp mạch tay trái 1 phút", "Bắt mạch người cao tuổi nếu có"],
        ["Đọc Mạch Kinh: Mach Sac (nhanh >5 nhip/ho hap)", "So sánh Trì vs Sác", "Bắt mạch sau vận động nhẹ"],
        ["Đọc Mạch Kinh: Mach Hu va Mach Thuc", "Cam nhan luc cua mach", "Bắt mạch + ghi lực (1-5)"],
        ["Đọc Mạch Kinh: Mach Hoat — tron tru nhu hat chau", "Tap nhan biet Hoat vs Sap", "Bắt mạch phu nu tre"],
        ["On 6 mach dau: Phu/Tram/Tri/Sac/Hu/Thuc/Hoat", "Tự mô tả lại từng mạch bằng lời", "Bắt mạch tổng hợp"],
        # Week 2
        ["Đọc Mạch Kinh: Mach Sap — tho rap khong tron", "So sánh Hoạt vs Sáp", "Bắt mạch người mệt mỏi"],
        ["Đọc Mạch Kinh: Mach Hong — to rong nhu song bien", "Tim mach Hong trong mua ha", "Bắt mạch + ghi biên độ"],
        ["Đọc Mạch Kinh: Mach Te — nho nhu soi chi", "So sánh Hồng vs Tế", "Bắt mạch người gầy"],
        ["Đọc Mạch Kinh: Mach Huyen — thang nhu day dan", "Tim mach Huyen o Can/Dom", "Bắt mạch Quan tay trái"],
        ["Đọc Mạch Kinh: Mach Khan — cang nhu day thua", "So sánh Huyền vs Khẩn", "Bắt mạch người đau"],
        ["Đọc Mạch Kinh: Mach Hoan — cham deu nhu mua thu", "Phan biet Hoan binh thuong vs benh ly", "Bắt mạch sau bữa ăn"],
        ["On mach Sap/Hong/Te/Huyen/Khan/Hoan", "Tự test: bắt mạch và đoán loại mạch", "Bắt mạch 5 người"],
        # Week 3
        ["Đọc Mạch Kinh: Mach Truong — truot dai qua 3 vi tri", "So sánh Trường vs Hoãn", "Bắt mạch + ghi độ dài"],
        ["Đọc Mạch Kinh: Mach Doan — khong du toi Quan hoac Xich", "Phan biet Truong vs Doan", "Bắt mạch người bệnh yếu"],
        ["Đọc Mạch Kinh: Mach Chuyen — mach tron xoay nhu day thua", "Tap nhan biet Chuyen", "Bắt mạch người đau bụng"],
        ["Đọc Mạch Kinh: Mach Dong — mach roi loan, giat cum", "Ghi chú biểu hiện lâm sàng", "Bắt mạch người hồi hộp lo lắng"],
        ["Đọc Mạch Kinh: Mach Lac — tu ngung roi tiep tuc deu", "Phan biet cac mach gian doan", "Bắt mạch người trung niên"],
        ["Đọc Mạch Kinh: Mach Dai — tu ngung khong deu, lau phuc lai", "So sánh Lạc vs Đại vs Kết", "Bắt mạch kỹ cẩn thận"],
        ["On tong tat 24 mach — tu test toan bo", "Vẽ bảng phân loại 24 mạch theo âm/dương", "Bắt mạch 10 người khác nhau"],
        # Week 4 — Mach theo tang phu
        ["Đọc Mạch Kinh Quyển 2: Mach theo Tang Phu — Tam Phe vi Thon", "Học vị trí 3 ngon tay Thon/Quan/Xich", "Bắt mạch phan biet ro 3 vi"],
        ["Mach Ty Vi ung voi Quan tay phai", "Ghi chú mach binh thuong Ty Vi theo mua", "Bắt mạch sau bữa ăn so sánh"],
        ["Mach Than Menh Mon ung Xich tay phai", "Ghi chú mach Thuong Han Luan ve Than", "Bắt mạch Xích tay phải + ghi"],
        ["Mach Can Dom ung Quan tay trai", "Học mạch Huyền ở Quan — bieu hien Can khi ult", "Bắt mạch buổi sáng sớm"],
        ["Mach Than Bang Quang ung Xich tay trai", "So sánh mạch Thận 2 tay", "Bắt mạch người nhiều tuổi"],
        ["Tong hop mach 6 vi tri — tu test khong nhin sach", "Ghi chú 3 người vừa bắt mạch + nhận định", "Bắt mạch + viết nhật ký mạch"],
        ["On tuan 4 — mach tang phu 6 vi", "Trả lời: Mạch Tỳ bình thường khác Tỳ hư như thế nào?", "Bắt mạch tổng hợp"],
        # Week 5 — Nan Kinh mach hoc
        ["Đọc Nan Kinh Nan 1-5: Thuoc mach, do dai, so nhip", "Ghi chú định nghĩa mạch bình thường Nan Kinh", "Bắt mạch dem chinh xac nhip"],
        ["Đọc Nan Kinh Nan 6-10: Am duong mach, Phuc mach, Phu mach", "So sánh với Mạch Kinh", "Bắt mạch người mệt sau làm việc"],
        ["Đọc Nan Kinh Nan 11-15: Mach co vat, mach that, thay doi theo mua", "Ghi chú mạch từ mùa", "Bắt mạch + doan mua hien tai"],
        ["Đọc Nan Kinh Nan 16-20: Mach tang + benh chung tuong ung", "Phân tích 5 loại mạch bệnh lý", "Bắt mạch người có bệnh mãn tính"],
        ["Đọc Nan Kinh Nan 21-22: Mach hinh vs mach khi", "Ghi chú phân biệt hình vs khí", "Bắt mạch 3 người + ghi hình/khí"],
        ["Chan Mac Yeu Quyet — toan bo (sach mong)", "Ghi chú 10 điểm Chẩn Mạch Yếu Quyết khác Mạch Kinh", "Bắt mạch + áp dụng Chẩn Mạch"],
        ["On tuan 5 — Nan Kinh mach hoc", "Tự đặt 10 câu hỏi về mạch học", "Bắt mạch + tra loi cac cau"],
        # Week 6 — Mach va lam sang
        ["Mach va benh Phong Han: Phu Khuan, Phu Sac, Phu Nhuoc", "Ghi chú phân biệt Phong Hàn Thương", "Bắt mạch khi troi lanh"],
        ["Mach va benh Nhiet: Sac Dai, Sac Hua, Hong Te", "Ghi chú mạch Nhiệt chứng", "Bắt mạch sau việc nặng"],
        ["Mach va benh Hu Lao: Te Nhuoc, Tram Te, Tu Tri", "Phân tích ngũ lao thất thương", "Bắt mạch người làm việc nhiều"],
        ["Mach va am uong: Hoat Thuc, Hoan Thai, Tram Hong", "Ghi chú mach thuc tich", "Bắt mạch 1h sau ăn cơm"],
        ["Mach va cam xuc: Huyen Khuan, Hong Dai, Tram Khan", "Lien he Can khi, Tam than, Phoi buon", "Bắt mạch khi stress"],
        ["Mach va xuat huyet: Sac/Nhuoc/Te/Khong Phu", "Hoc mach thiet hiet tu can", "Bắt mạch + ghi nhật ký chi tiết"],
        ["On tuan 6 — mach lam sang", "Viet 3 ca lam sang tu kien/tue/kinh nghiem", "Bắt mạch tổng hợp"],
        # Week 7 — Mach kho va dac biet
        ["Mach that 7 loai — Bi Hu Tuyet, Que, Quach, Tan, Giai, Pha, Tuong", "Ghi chú ý nghĩa từng mạch", "Hiểu chỉ, không tập bắt"],
        ["Mach Bat Tuong: 8 mach ky kinh va mach tuong ung", "Ve so do mach bat tuong", "Bắt mạch + tim dac diem ky kinh"],
        ["Mach Thai Ky (mach thai san)", "Ghi chú đặc điểm mạch phụ nữ có thai", "Bắt mạch phụ nữ nếu có thể"],
        ["Mach Lao (mach nguoi cao tuoi)", "Phan biet mach lao binh thuong vs benh ly", "Bắt mạch người trên 60"],
        ["Mach Xuat Huyet nao — nhan biet cap cuu", "Ghi chú 3 mạch cảnh báo nguy hiểm", "Hieu ly thuyet, khong thuc hanh cap cuu"],
        ["On mach kho va dac biet", "Tóm tắt bảng phân loại mạch theo mức độ nghiêm trọng", "Bắt mạch tổng hợp + ghi danh gia"],
        ["Tự test: mô tả mạch không nhìn sách", "Mô tả bằng lời 10 loại mạch ngẫu nhiên", "Bắt mạch va doan chuan xac"],
        # Week 8 — Thuc hanh chuyen sau
        ["Bắt mạch buổi sáng: ghi nhịp, lực, độ sâu, hình thái", "Nhật ký mạch học: ghi đầy đủ 4 thông số", "Phân tích từ mạch bản thân"],
        ["Bắt mạch buổi tối: so sánh với sáng", "Ghi chú sự thay đổi trong ngày", "Phân tích nguyên nhân thay đổi"],
        ["Bắt mạch sau khi uống cà phê/trà", "Ghi chú ảnh hưởng Thực chất lên mạch", "Liên hệ lý thuyết Khí hóa"],
        ["Bắt mạch sau tập thể dục 30 phút", "Ghi chú thay đổi mạch post-exercise", "Liên hệ Dương Khí vận động"],
        ["Bắt mạch trước và sau ăn trưa", "Ghi chú tác động Tỳ Vị lên mạch", "Phân tích: có đúng lý thuyết không?"],
        ["Bắt mạch trong các trạng thái cảm xúc khác nhau", "Ghi chú Can khí vs Tâm thần trên mạch", "Viet nhat ky phan tich"],
        ["On tuan 8 — nhat ky mach hoc 7 ngay", "Tìm quy luật cá nhân từ nhật ký mạch", "Bắt mạch + ghi tổng kết"],
        # Week 9 — Ket hop ly thuyet
        ["Đọc lại Mạch Kinh Quyển 3: Bien chung mach benh ly", "Ghi chú 10 biến chứng quan trọng", "Bắt mạch + áp dụng biện chứng"],
        ["Tổng hợp: mạch Phủ Tạng bệnh lý", "Vẽ bảng mạch ↔ chứng tương ứng", "Bắt mạch + nhận định tang bi anh huong"],
        ["Tổng hợp: mạch Phong Hàn Nhiệt Thấp", "Phân biệt 4 ngoại tác qua mạch", "Bắt mạch vào các thời điểm khác nhau"],
        ["Tổng hợp: mạch Khí Huyết Âm Dương hư", "Ghi chú quy tac phan biet", "Bắt mạch 5 người + nhận định"],
        ["Đọc Nan Kinh Nan 1-22 lan 2 — doc lai voi mat mach hoc", "Ghi chú diem moi phat hien", "Bắt mạch + ứng dụng Nan Kinh"],
        ["So sanh Mach Kinh vs Nan Kinh: 5 diem khac biet chinh", "Viet bai phan tich ngan", "Bắt mạch + ghi nhat ky"],
        ["On tuan 9 — ly thuyet ket hop", "Tự test 20 câu hỏi tổng hợp", "Bắt mạch tổng hợp"],
        # Week 10 — Chuan bi thi
        ["On mach 24 loai — mo ta va nhan biet", "Lam flashcard 24 mach", "Bắt mạch + test flashcard"],
        ["On mach theo tang phu 6 vi", "Vẽ lại từ trí nhớ bản đồ mạch 6 vị", "Bắt mạch 3 người + ghi nhận định"],
        ["On Nan Kinh mach hoc Nan 1-22", "Tóm tắt 22 nan thành 1 trang", "Bắt mạch + áp dụng"],
        ["On mach lam sang 6 chu de", "Viet 5 ca lam sang ngan", "Bắt mạch + chẩn đoán thử"],
        ["On mach kho va dac biet", "Kiem tra lai cac diem yeu", "Bắt mạch tổng hợp"],
        ["Lam de thi thu 80 cau mach hoc", "Ghi chú cac cau sai", "Bắt mạch + ghi kết quả"],
        ["On lai cac cau sai — phan tich nguyen nhan", "Hiểu sâu từng câu sai", "Bắt mạch + nghỉ sớm"],
        # Week 11
        ["Kiem tra toan dien mach hoc — 160 cau tu trac nghiem", "Ghi chú diem yeu con lai", "Bắt mạch tổng hợp"],
        ["On nhom 1: Am Duong mach (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On nhom 2: Mach Tang Phu (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On nhom 3: Mach benh ly (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On nhom 4: Nan Kinh mach hoc (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On tong luc — tat ca diem yeu", "Nghi som, ngu du giac", "Bắt mạch nhẹ"],
        ["Nghi — khong hoc moi", "Thien 20 phut, toan than thu gian", "Cam nhan mach chinh minh"],
        # Week 12
        ["On cuoi: Mach Kinh Quyen 1 + 2 + 3 toan bo", "Doc nhanh, danh dau diem cot yeu", "Bắt mạch"],
        ["On cuoi: Nan Kinh Nan 1-22 + Chan Mac Yeu Quyet", "Tóm tắt 1 trang mỗi sách", "Bắt mạch"],
        ["On cuoi: Mach lam sang + ca lam sang", "Viet 3 ca lam sang moi tu kinh nghiem", "Bắt mạch người thân"],
        ["On cuoi: Mach kho + mach dac biet", "Kiem tra lai lan cuoi", "Bắt mạch + đánh giá bản thân"],
        ["Tong on — lam 40 cau ngau nhien", "Chữa sai, ghi chú cuối cùng", "Bắt mạch + cảm ơn cuộc hành trình"],
        ["Nghi ngoi va on nhe", "Nghi som, thu gian tam ly", "Bắt mạch 10 phút nhẹ nhàng"],
        ["Ngày thi Phase 1 — bot sẽ gửi đề thi hôm nay", "Giu tam binh tinh, tin vao thuc hanh 84 ngay", "Bắt mạch trước khi thi"],
    ],

    2: [  # Phase 2 — 20 weeks = 140 days — Cham Cuu Chuyen Sau
        # Week 1 — Cham Cuu Dai Thanh Q1: 14 kinh chinh huyet vi
        ["Đọc Châm Cứu Đại Thành Q1: Mo dau, lich su cham cuu", "Ghi chú 10 mốc lịch sử châm cứu quan trọng", "Bắt mạch + liên hệ kinh mạch"],
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Thu Thai Am Phe — 11 huyet", "Vẽ đường kinh Phế + ghi tên 11 huyệt", "Tim vi tri Trung Phu, Vun Mon tren co the"],
        ["Học vị trí 11 huyệt kinh Phế trên cơ thể", "Ghi chú chỉ định điều trị của mỗi huyệt", "Tap bam diem xac dinh vi tri huyet"],
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Thu Duong Minh Dai Truong — 20 huyet", "Vẽ đường kinh + 20 huyệt", "Tim Hop Coc, Khuc Tri tren tay"],
        ["Học vị trí 20 huyệt kinh Đại Trường", "Ghi chú chỉ định điều trị", "Bấm Hợp Cốc — cảm nhận Đắc Khí"],
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Tuc Duong Minh Vi — 45 huyet", "Vẽ đường kinh Vị + 45 huyệt", "Tim Tuc Tam Ly, Phong Long tren chan"],
        ["On tuan 1 — 3 kinh dau (Phe/Dai Truong/Vi)", "Vẽ lại từ trí nhớ, ghi diem quan trong nhat", "Bắt mạch + liên hệ 3 kinh"],
        # Week 2
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Tuc Thai Am Ty — 21 huyet", "Vẽ đường kinh Tỳ + 21 huyệt", "Tim Tam Am Giao, Hoan Khe"],
        ["Học vị trí huyệt Tam Âm Giao, Địa Cơ, Hoàn Khê, Huỳnh Môn, Đại Bao", "Ghi chú chỉ định của từng huyệt", "Bấm Tam Âm Giao — ghi cảm nhận"],
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Thu Thieu Am Tam — 9 huyet", "Vẽ đường kinh Tâm + 9 huyệt", "Tim Tam kinh tren tay"],
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Thu Thai Duong Tieu Truong — 19 huyet", "Vẽ đường kinh + 19 huyệt", "Tim Thieu Trach, Hau Khe"],
        ["Học vị trí 9 huyệt Tâm + 19 huyệt Tiểu Trường quan trọng nhất", "Ghi chú chỉ định điều trị", "Bấm điểm + ghi cảm nhận"],
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Tuc Thai Duong Bang Quang — 67 huyet", "Vẽ đường kinh + ghi tên 67 huyệt", "Tim Du Huyyet cua cac tang"],
        ["On tuan 2 — Ty/Tam/Tieu Truong/Bang Quang", "Vẽ lại từ trí nhớ 4 kinh", "Bắt mạch + liên hệ 4 kinh vừa học"],
        # Week 3
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Tuc Thieu Am Than — 27 huyet", "Vẽ đường kinh Thận + 27 huyệt", "Tim Duong Tuyen, Phuc Luu tren chan"],
        ["Hoc Vi Du, Can Du, Phe Du, Tam Du, Than Du — ngu tang du huyet", "Ghi chú chi dinh tung Du huyet", "Bấm nhẹ Du huyệt trên lưng"],
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Thu Quyet Am Tam Bao — 9 huyet", "Vẽ đường kinh Tâm Bao + 9 huyệt", "Tim Lao Cung, Noi Quan"],
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Thu Thieu Duong Tam Tieu — 23 huyet", "Vẽ đường kinh Tam Tiêu + 23 huyệt", "Tim Ngoai Quan, Dan Trung huyet"],
        ["Học vị trí Nội Quan, Ngoại Quan — cap huyet doi nhau", "Ghi chú so sánh chỉ định 2 huyệt", "Bấm Nội Quan + Ngoại Quan"],
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Tuc Thieu Duong Dom — 44 huyet", "Vẽ đường kinh Đởm + 44 huyệt", "Tim Phong Thi, Dich Truyen, Duong Lang Tuyen"],
        ["On tuan 3 — Than/Tam Bao/Tam Tieu/Dom", "Vẽ lại từ trí nhớ 4 kinh moi", "Bắt mạch + nhận định luc phf tang hom nay"],
        # Week 4
        ["Đọc Châm Cứu Đại Thành Q1: Kinh Tuc Quyet Am Can — 14 huyet", "Vẽ đường kinh Can + 14 huyệt", "Tim Thai Xung, Hanh Gian"],
        ["Đọc Châm Cứu Đại Thành Q1: Mach Doc — 28 huyet", "Vẽ Mạch Đốc từ Trường Cường lên Nguyên Hội", "Tim Bach Hoi, Phong Phu, Nhan Trung"],
        ["Đọc Châm Cứu Đại Thành Q1: Mach Nham — 24 huyet", "Vẽ Mạch Nhâm từ Hội Âm lên Thừa Tương", "Tim Quan Nguyen, Khi Hai, Trung Wan"],
        ["Học 8 Kỳ Kinh: tên và đường đi cơ bản", "Vẽ sơ đồ 8 kỳ kinh đơn giản", "Bấm Bách Hội + Trung Quản + Quan Nguyên"],
        ["On toan bo 14 kinh chinh + Mach Doc + Mach Nham", "Kiem tra lai tat ca ten huyet da hoc", "Vẽ lại bản đồ cơ thể tất cả kinh"],
        ["Linh Khu Chuong 12: Kinh Biet — 12 duong kinh phu", "Ghi chú ý nghĩa Kinh Biệt trong lâm sàng", "Bắt mạch + liên hệ Kinh Biệt"],
        ["On tuan 4 — Can/Doc/Nham + tong ket 14 kinh", "Tự test 30 câu hỏi vị trí huyệt", "Bắt mạch tổng hợp"],
        # Week 5 — Cham Cuu Dai Thanh Q2: Thu phap
        ["Đọc Châm Cứu Đại Thành Q2: Thu phap co ban — Tiet khau, Tich khau", "Ve goc cam kim dung cho tung vi tri", "Tap tren bo-tui/cam cam"],
        ["Đọc Châm Cứu Đại Thành Q2: Dac Khi — cam giac khi da khi", "Ghi chú mô tả Đắc Khí: tức, nóng, lan, điện", "Bấm điểm + tự mô tả cảm giác"],
        ["Đọc Châm Cứu Đại Thành Q2: Bo phap va Ta phap", "Ghi chú quy tắc Bổ — Tả theo Nan Kinh", "Phân tích: khi nào Bổ, khi nào Tả?"],
        ["Đọc Châm Cứu Đại Thành Q2: Cuu phap (ngai cuu)", "Ghi chú cách làm cứu điểm và cứu trực tiếp", "Hiểu lý thuyết, không thực hành cứu"],
        ["Đọc Châm Cứu Đại Thành Q2: Phoi huyet ca ban — Nguyen-Lac, Du-Mo", "Ghi chú quy tắc phối Nguyên-Lạc", "Ap dung: Ty huu phoi Tam Am Giao + Cong Ton"],
        ["Đọc Châm Cứu Đại Thành Q2: Ngu Du huyet — Tinh Huynh Du Kinh Hop", "Ghi chú Ngũ hành tương ứng của Ngũ Du", "Vẽ bảng Ngũ Du 12 kinh"],
        ["On tuan 5 — thu phap + Dac Khi + Bo Ta", "Tự đặt 10 câu hỏi về thủ pháp", "Thảo luận với bạn học nếu có"],
        # Week 6 — Hoang De Minh Duong Cham Kinh
        ["Đọc Hoàng Đế Minh Đường Châm Kinh: Mo dau, lich su", "So sanh voi Cham Cuu Dai Thanh", "Ghi chú điểm khác biệt cơ bản"],
        ["Hoang De Minh Duong: Huyet Vi goc cua 14 kinh (khac so voi Cham Cuu Dai Thanh)", "Ghi chú 10 huyet vi tri khac biet", "Bắt mạch + lien he vi tri huyet co dien"],
        ["Hoang De Minh Duong: Cam Dac Khi co dien — mo ta trong van ban", "So sanh voi mo ta hien dai", "Bấm Túc Tam Lý + tự mô tả cảm giác"],
        ["Linh Khu Chuong 2: Ban Thu — Bien chung, ngu nhan cham", "Ghi chú 5 nguyên tắc cấm châm", "Phan tich: khi nao khong cham?"],
        ["Linh Khu Chuong 3: Tieu Cham — 9 loai kim co dien", "Vẽ 9 loại kim + công dụng", "Hiểu lịch sử, liên hệ kim hiện đại"],
        ["Linh Khu Chuong 4: Buu Khi — Khi cua huyet va kim", "Ghi chú lý thuyết Khí tương tác với kim", "Thien + cam nhan Khi tai Bach Hoi"],
        ["On tuan 6 — Hoang De Minh Duong + Linh Khu", "Ghi chú 5 phát hiện quan trọng nhất tuần này", "Bắt mạch tổng hợp"],
        # Week 7 — Phoi huyet lam sang
        ["Phoi huyet cho benh dau dau: Bach Hoi, Thai Duong, Phong Tri, Hop Coc", "Hiểu cơ chế mỗi huyệt", "Bấm tự phát Phong Trì + Hợp Cốc"],
        ["Phoi huyet cho benh mat ngu: Tam Mo, An Mien, Shen Men, Tam Am Giao", "Ghi chú cơ chế 4 huyệt này", "Bấm An Miên + Thần Môn buổi tối"],
        ["Phoi huyet cho tinh than: Bach Hoi, Noi Quan, Thai Xung, Tam Mo", "Hieu 'Hai vai giang than' trong cham cuu", "Thien + cam nhan 4 huyet"],
        ["Phoi huyet cho ho hap: Phe Du, Trung Phu, Phong Mon, Dinh Chuan", "Phan tich 4 tang o Bo phap Phe", "Hoc hoi tho sau co dich"],
        ["Phoi huyet cho tieu hoa: Tuc Tam Ly, Trung Wan, Ty Du, Vi Du", "Ghi chú cơ chế Tỳ Vị khí hóa", "Bấm Túc Tam Lý buổi sáng"],
        ["Phoi huyet cho dau lung: Than Du, Wei Zhong (Ui Trung), Kun Lun (Khon Luan)", "Học tam hoàng bảo (back shu + command point)", "Bấm nhẹ Thận Du + Ủy Trung"],
        ["On tuan 7 — phoi huyet lam sang 6 chu de", "Viet 3 ca lam sang ngan tu phoi huyet vua hoc", "Bắt mạch + nhận định kien nghi"],
        # Week 8 — Kinh Can va Kinh Biet
        ["Linh Khu Chuong 13: Kinh Can — he thong co mac", "Ghi chú 12 Kinh Can + anh huong", "Liên hệ Kinh Cân với fascia hiện đại"],
        ["Phan tich Kinh Can Duong Minh: lien he mat truoc toan than", "Vẽ sơ đồ Kinh Cân Dương Minh", "Cam nhan co tru truoc co the"],
        ["Phan tich Kinh Can Thai Duong: lien he mat sau toan than", "Vẽ sơ đồ Kinh Cân Thái Dương", "Cam nhan co tru sau co the"],
        ["Phan tich Kinh Can Thieu Duong: lien he mat ben toan than", "Vẽ sơ đồ Kinh Cân Thiếu Dương", "Cam nhan co tru ben co the"],
        ["Ứng dụng Kinh Cân trong điều trị đau cơ xương khớp", "Ghi chú 5 tình huống điều trị", "Phân tích: phương châm Kinh Cân vs Kinh Chính"],
        ["Linh Khu Chuong 11: Kinh Biet — moi noi 6 hop", "Vẽ sơ đồ 6 Hợp của Kinh Biệt", "Hieu y nghia Kinh Biet trong benh noi tang"],
        ["On tuan 8 — Kinh Can + Kinh Biet", "Ghi chú 10 điểm quan trọng nhất", "Bắt mạch + liên hệ kinh lạ"],
        # Week 9
        ["Loa Cham (nhi cham): so do tai + diem tuong ung", "Học 10 điểm tai quan trọng nhất", "Bấm điểm tai tác giải đau đầu"],
        ["Vuong Chau Cham (cham tren mat): so do mat", "Học 5 điểm mặt cơ bản", "Ghi chú lich su vuong chau cham"],
        ["Duoi Cham (cham chan sau): 14 diem co ban", "Học vị trí 14 điểm Dưới Châm", "Bấm nhẹ lòng bàn chân + cảm nhận"],
        ["Nhan trung + Bach Hoi + Noi Quan — bo 3 huyet an than", "Ghi chú chi dinh dac biet", "Bấm tự nhân trung khi mệt mỏi"],
        ["Hoc cham cuu theo thoi gian — Linh Quy Bat Phap", "Ghi chú nguyên tắc chọn giờ châm", "Xác định giờ và huyệt cho ngày hôm nay"],
        ["Hoc cham cuu theo thoi gian — Ngo Xa Luu Chu", "So sanh Linh Quy vs Ngo Xa", "Ghi chú ưu nhược điểm mỗi phương pháp"],
        ["On tuan 9 — nhi cham + bo sung phap", "Ghi chú 5 phương pháp châm cứu bổ sung đã học", "Bắt mạch + nhận định"],
        # Week 10
        ["Thieu Am Cham Phap — 8 phap cua Tam va Than", "Ghi chú chi dinh 8 phap", "Phan tich: khi nao dung Thieu Am Cham?"],
        ["Binh Diem Cham Phap — cham diem hoa xuong", "Học 20 điểm hoa xương cơ bản", "Bắt mạch + liên hệ cơ xương"],
        ["Tổng hợp phối huyệt nâng cao: Mộ-Du-Lạc-Nguyên", "Ghi chú quy tac phoi 4 loai huyet nang cao", "Ap dung: phac do benh Ty huu"],
        ["Ung dung Ngu Du huyet theo Ngo Hanh bi thang (mother-son)", "Tinh huyet cho Phe huu = bo Ty (Thai Bai) + ta Tam (Thieu Phu)", "Thực hành tính huyệt một bệnh"],
        ["Phan tich bien chung cham cuu: 8 tinh huong cam cham", "Ghi chú xử lý tai biến", "Hiểu lý thuyết an toàn"],
        ["On tuan 10 — phap cham nang cao", "Tự test 20 câu hỏi phối huyệt", "Bắt mạch tổng hợp"],
        ["Nghi — thien + cam nhan Khi sau 10 tuan hoc cham", "Viet nhat ky: su thay doi tu nhan thuc ve co the", "Cam nhan toan than"],
        # Week 11-15: Chuyen sau lam sang
        ["Cham cuu benh ho hap: Viem mui di ung — phac do 5 huyet", "Ghi chú co che moi huyet", "Bắt mạch + nhận định Phe Khi"],
        ["Cham cuu benh ho hap: Hen suyen man tinh — phac do 6 huyet", "Phan tich Bo vs Ta trong hen suyen", "Ap dung ly thuyet Phe Ty Than"],
        ["Cham cuu benh tieu hoa: Viem dai trang co nang — phac do", "Hoc quy tac phoi Ty Vi tren/duoi", "Bắt mạch + ghi nhận định Tỳ Vị"],
        ["Cham cuu benh tieu hoa: Tao bon man tinh — phac do 4 huyet", "Phan biet tao bon Khi huu vs Am huu", "Ap dung bien chung chon phac do"],
        ["Cham cuu benh xuong khop: Dau vai — kinh Tieu Truong + Dom", "Hoc diem ashi + kinh duong", "Bắt mạch + phân tích kinh bi thuong"],
        ["Cham cuu benh xuong khop: Dau that lung — kinh Than/Bang Quang", "Hoc phac do dau lung cap/man", "Bấm Ủy Trung + Thận Du nhẹ"],
        ["On tuan 11 — ho hap + tieu hoa + xuong khop", "Viet 3 ca lam sang day du", "Bắt mạch 3 ca"],
        ["Cham cuu benh than kinh: Dau dau Migraine — phac do", "Học Thiếu Dương + Dương Minh cho migraine", "Bấm Phong Trì + Nội Quan"],
        ["Cham cuu benh than kinh: Mat ngu — phac do 5 huyet + cuu", "Ghi chú ket hop cham + cuu cho mat ngu", "Bấm An Miên buổi tối"],
        ["Cham cuu tram cam nhe: Bach Hoi, Noi Quan, Thai Xung, Tam Mo, Trung Wan", "Hoc 'Hai co giang than' cho tram cam", "Thien + bam 5 huyet tren"],
        ["Cham cuu benh phu khoa: Roi loan kinh nguyet — phac do Can Ty Than", "Ghi chú bien chung Can huu, Tam Huyet huu", "Bắt mạch tay trai phu nu"],
        ["Cham cuu pho tro sut can: Nhi cham + kinh Ty Vi", "Học phác đồ nhi châm 5 điểm", "Bấm điểm tai cho Tỳ Vị"],
        ["Cham cuu ha huyet ap: Phe Du, Tam Du, Noi Quan, Tuc Tam Ly", "Ghi chú co che on dinh huyet ap qua Khi hoa", "Bắt mạch + do huyet ap neu co the"],
        ["On tuan 12-13 — benh than kinh + phu khoa + noi tiet", "Viet 5 ca lam sang day du 5 chu de", "Bắt mạch 5 người"],
        # Week 14-15: Tong hop va chuan bi thi
        ["Tổng ôn Châm Cứu Đại Thành Q1: 14 kinh chinh + 361 huyet quan trong", "Lam flashcard 50 huyet co ban nhat", "Bắt mạch + nhận định kinh nao hoat dong nhat"],
        ["Tổng ôn Châm Cứu Đại Thành Q2: Thu phap + Bo Ta + Ngu Du", "Tu test 20 cau hoi thu phap", "Thực hành bổ tả pháp trên bản thân"],
        ["Tổng ôn Hoàng Đế Minh Đường + Linh Khu Kinh Mạch", "Vẽ lại 14 kinh cơ bản từ trí nhớ", "Bắt mạch tổng hợp"],
        ["Tổng ôn phối huyệt lâm sàng: 10 bệnh phổ biến", "Viết 10 phác đồ ngắn gọn", "Bắt mạch + chẩn đoán thử"],
        ["Tổng ôn châm đặc biệt: nhĩ châm, dưới châm, bổ sung pháp", "Tóm tắt 1 trang", "Thien + cam nhan Khi"],
        ["Lam de thi thu 80 cau cham cuu", "Ghi chú cac cau sai", "Bắt mạch"],
        ["On lai cac cau sai — phan tich nguyen nhan", "Hiểu sâu từng câu sai", "Bắt mạch + nghỉ sớm"],
        # Week 16-17: On thi
        ["On thi: Vi tri huyet 14 kinh (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On thi: Thu phap + Bo Ta + Ngu Du (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On thi: Phoi huyet lam sang (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On thi: Cham dac biet + Kinh Biet + Kinh Can (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On thi lan 2: Vi tri huyet 14 kinh", "Ghi chú diem yeu con lai", "Bắt mạch"],
        ["On thi lan 2: Thu phap + lam sang", "Ghi chú diem yeu con lai", "Bắt mạch"],
        ["Nghi — thien + on nhe", "Cam on ban than vi 140 ngay kien tri", "Bắt mạch + nghỉ sớm"],
        # Week 18
        ["On tong luc — tat ca diem yeu", "Lam 40 cau ngau nhien lan cuoi", "Bắt mạch"],
        ["Kiem tra ky nang thuc hanh: xac dinh vi tri 20 huyet quan trong", "Tu danh gia do chinh xac", "Bam diem + cam nhan Dac Khi"],
        ["On phoi huyet: 10 benh pho bien — phac do nhanh", "Viet lai phac do khong nhin tai lieu", "Bắt mạch + nhận định"],
        ["On thu phap + an toan cham cuu", "Kiem tra lai quy tac cam cham", "Hiểu sâu an toàn trước thực hành"],
        ["Tổng ôn cuối — mỗi phần 30 phút", "Ghi chú tu tin vao tung phan", "Bắt mạch tổng hợp"],
        ["Nghi ngoi + chuan bi tam ly", "Ngu du giac, khong on khuya", "Bắt mạch buoi sang binh thuong"],
        ["Ngày thi Phase 2 — bot sẽ gửi đề thi hôm nay", "Giu tam binh tinh, tin vao 140 ngay hoc", "Bắt mạch trước khi thi"],
    ] + [  # padding to exactly 140 entries (20 weeks × 7 = 140)
        [f"Ôn tập Châm Cứu ngày {i+1}", "Ghi chú 3 diem can on", "Bắt mạch + liên hệ lý thuyết"]
        for i in range(140 - 20*7)  # fills any gap if above is short
    ],

    3: [  # Phase 3 — 32 weeks = 224 days — Thuong Han & Tap Benh
        # Week 1 — Thuong Han Luan: Thai Duong kinh
        ["Đọc Thương Hàn Luận: Mo dau, Luc kinh he thong", "Ghi chú 6 kinh biện chứng cơ bản", "Bắt mạch + nhận định khi nao dung luc kinh"],
        ["Đọc Thương Hàn Luận: Thai Duong kinh — Dieu 1-10", "Ghi chú chứng trúng phong vs chứng thương hàn", "Bắt mạch: tim Phu Khuan, Phu Hoan"],
        ["Đọc Thương Hàn Luận: Thai Duong kinh — Dieu 11-30: Que Chi thang bien bien", "Hoc 3 phuong tieu Que Chi", "Ghi chú: khi nào thêm/bớt thuốc trong Quế Chi thang"],
        ["Đọc Thương Hàn Luận: Thai Duong kinh — Dieu 31-60: Ma Hoang thang + bien bien", "Phan biet Ma Hoang vs Que Chi chi dinh", "Bắt mạch: Phu Khuan (phong) vs Phu Khun (han)"],
        ["Đọc Thương Hàn Luận: Thai Duong kinh — Dieu 61-100: Bien bien phuc tap", "Ghi chú 10 phương quan trọng nhất", "Ap dung bien bien: nguoi sot khong ra mo hoi"],
        ["Đọc Thương Hàn Luận: Thai Duong kinh — Dieu 101-130: Nhap ly bien bien", "Ghi chú điều kiện chuyển kinh", "Bắt mạch: Phu Dai — am nhiet tu Thai Duong"],
        ["On tuan 1 — Thai Duong kinh Dieu 1-130", "Viet tom tat co che Thai Duong benh", "Bắt mạch tổng hợp"],
        # Week 2
        ["Đọc Thương Hàn Luận: Thai Duong kinh — Dieu 131-180: Bien chung nang hon", "Ghi chú bệnh hãm hung, kết hung", "Bắt mạch: Tram Khun — am sung benh ly"],
        ["Đọc Thương Hàn Luận: Thai Duong kinh — Dieu 181-220", "Hoan thanh Thai Duong phan", "Tóm tắt Thái Dương: 3 để tiếp cận"],
        ["Học Quế Chi thang — phân tích 6 vị thuốc", "Ghi chú cơ chế hoạt động của từng vị", "Bắt mạch Phu Hoan — chi dinh Que Chi"],
        ["Học Ma Hoàng thang — phân tích 4 vị thuốc", "So sanh Ma Hoang vs Que Chi co che", "Bắt mạch Phu Khun — chi dinh Ma Hoang"],
        ["Học Ma Hoàng Quế Chi Các Bán Thang — giai giai trung gian", "Ghi chú biến biến phong vs hàn còn lại", "Bắt mạch + phân tích Phu Nhuoc vs Phu Khun"],
        ["Học Sài Hồ thang — Thiếu Dương chủ phương", "Ghi chú 7 chứng trung thường của Sài Hồ thang", "Bắt mạch Huyen — chi dinh Sai Ho"],
        ["On tuan 2 — Ma Hoang, Que Chi, Sai Ho, + bien bien co ban", "Tự test 10 câu biện biến", "Bắt mạch tổng hợp"],
        # Week 3 — Duong Minh kinh
        ["Đọc Thương Hàn Luận: Duong Minh kinh — Dieu 179-210", "Ghi chú Kinh chứng vs Phủ chứng", "Bắt mạch: Thuc Dai, Tram Thuc — Duong Minh"],
        ["Đọc Thương Hàn Luận: Duong Minh kinh — Dieu 211-250", "Học Ngũ Linh Tán — thanh nhiệt cho phép", "Bắt mạch Hoan Dai — vong tham"],
        ["Học Bạch Hổ thang — Thạch Cao thanh nhiệt phế nhiệt", "Phân tích Bạch Hổ vs Thạch Cao chỉ định", "Bắt mạch Hoan Dai + Sac Dai"],
        ["Học Điều Vị Thang (Bạch Hổ Thừa Nhâm Thang) — duong am nhiet", "Phan biet Nhiet vs Am huu Duong Minh", "Bắt mạch + cham doan Duong Minh"],
        ["Học 3 Thừa Khí thang: Đại/Tiểu/Điều Vị", "Ghi chú chi dinh tung phuong qua trieu chung phu tuc", "Bắt mạch: Tram Thuc Dai + trieu chung"],
        ["On tuan 3 — Duong Minh kinh", "Viet so do bien chung Duong Minh", "Bắt mạch tổng hợp"],
        ["Học Hợp Đồng thang — Túc Thiếu Dương kinh hệ", "Phan tich 6 phuong Tuc Thieu Duong", "Bắt mạch Huyen Te — Thieu Duong huu"],
        # Week 4 — Thieu Duong + Thai Am kinh
        ["Đọc Thương Hàn Luận: Thieu Duong kinh — Dieu 263-272", "Ghi chú tam chứng + tứ cấm", "Bắt mạch Huyen Khun — Thieu Duong chinh mac"],
        ["Học Sài Hồ Quế Chi Can Khương thang — Thieu Duong vao Tang", "Phan tich co che Sai Ho bien phuong", "Bắt mạch + nhận định Tang bi anh huong"],
        ["Đọc Thương Hàn Luận: Thai Am kinh — Dieu 273-280", "Ghi chú Thai Am thuong han trieu chung", "Bắt mạch Hoan Te — Thai Am"],
        ["Học Lý Trung thang — Bổ trung ích Tỳ khí", "Phan tich Ly Trung 4 vi + co che", "Bắt mạch + phân tích huu Ty Khi"],
        ["Học Trừ Bùi thang — giữ hàn ở trong kinh", "Ghi chú điều kiện chỉ định trừ bùi", "Bắt mạch Tram Hoan + lanh bung"],
        ["Học Tứ Nghịch thang — hồi dương cứu nghịch", "Phan tich 3 bien bien Tu Nghich thang", "Bắt mạch Tu Tram — Duong huu"],
        ["On tuan 4 — Thieu Duong + Thai Am + phuong tieu", "Viet so do 3 kinh vua hoc", "Bắt mạch tổng hợp"],
        # Week 5 — Thieu Am + Quyet Am kinh
        ["Đọc Thương Hàn Luận: Thieu Am kinh — Dieu 281-325", "Ghi chú Thiếu Âm: Hàn hóa và Nhiệt hóa", "Bắt mạch Te + Te Sac"],
        ["Học Ma Hoàng Phụ Tử Thiếu Âm Thang — am han Thieu Am", "Phan tich Ma Hoang Phu Tu co che", "Bắt mạch Te Tram — Thieu Am han"],
        ["Học Hoàng Liên A Giao thang — âm nhiệt Thiếu Âm", "So sanh Han hoa vs Nhiet hoa Thieu Am", "Bắt mạch Te Sac — Thieu Am nhiet"],
        ["Đọc Thương Hàn Luận: Quyet Am kinh — Dieu 326-381", "Ghi chú Quyết Âm nóng lạnh lẫn lộn", "Bắt mạch Quyet + Huan"],
        ["Học Ô Mai thang — Quyết Âm phức tạp", "Phan tich Vu Mai thang 10 vi", "Bắt mạch + nhận định Can Tam Nhu Toan"],
        ["Học Dương Phục thang — khí quỹ dương nghịch", "Ghi chú cơ chế dương khí xu hướng", "Bắt mạch Tram — duong am huu"],
        ["On tuan 5 — Thieu Am + Quyet Am", "Vẽ sơ đồ 6 kinh biện chứng đầy đủ", "Bắt mạch tổng hợp"],
        # Week 6 — Tap benh Luan
        ["Đọc Tứ Thánh Tâm Nguyên: Duong Khi & Menh Mon — Quyen 1", "Ghi chú Hoàng Nguyên Ngự lý thuyết Dương Khí", "Bắt mạch + lien he Menh Mon"],
        ["Đọc Tứ Thánh Tâm Nguyên: Phe Khi & Trung Tieu — Quyen 2", "Phân tích Trung Khí khai thông Phế Khí", "Bắt mạch Thốn tay phải + nhận định Phế"],
        ["Đọc Tứ Thánh Tâm Nguyên: Ty Vi ly luan — Quyen 3", "Ghi chú quan điểm Hoàng Nguyên Ngự về Trung Tiêu", "Bắt mạch Quan tay phai + nhan dinh Vi"],
        ["Đọc Tứ Thánh Tâm Nguyên: Than Khi & Menh Mon — Quyen 4", "Phân tích Thận Âm vs Thận Dương — quan diem Hoang Nguyen Ngu", "Bắt mạch Xích 2 tay"],
        ["Đọc Tạp Bệnh Luận — Truong Trong Canh: Tong quan Kim Quuy Yeu Luoc", "Ghi chú 6 phần trọng của Kim Quỹ", "Bắt mạch"],
        ["Đọc Kim Quỹ Yeu Luoc: Bien chung Hu Lao — Huu Gui Thang", "Học Hữu Quy Thang cơ chế bổ Thận Dương", "Bắt mạch Xich Nhuoc + nhan dinh Than Duong huu"],
        ["On tuan 6 — Tu Thanh Tam Nguyen + Kim Quuy", "Ghi chú 5 điểm quan trọng nhất", "Bắt mạch tổng hợp"],
        # Week 7-10: Kim Quuy Yeu Luoc — bien chung tap benh
        ["Đọc Kim Quỹ: Bien chung am bo truong chi benh — Viet Bi thang", "Học Việt Tỳ thang + biến biến", "Bắt mạch Phu Tram Khun"],
        ["Đọc Kim Quỹ: Bien chung Hung Bi — Qua Lou Xie Bai thang", "Học Hung Tý âm hàn vs nhiệt ứng", "Bắt mạch Tram Khun — Hung Bi"],
        ["Đọc Kim Quỹ: Bien chung Khi Nen — Kim Quy Shen Khi Wan", "Học Thận Khí Hoàn cơ chế", "Bắt mạch Xich Nhuoc — Than am"],
        ["Đọc Kim Quỹ: Bien chung phu tu Menh Mon — Wen Jing thang", "Học Ôn Kinh thang bí mật cho phụ từ Mệnh Môn hư", "Bắt mạch + phân tích Can Huyet huu phu nu"],
        ["Đọc Kim Quỹ: Bien chung thuy ung — 5 loai thuy ung", "Phan biet Phong/Phu/Chinh/Thach/Hoang Hoa thuy", "Bắt mạch + nhận định thuy huu"],
        ["Đọc Kim Quỹ: Bien chung hung ung ho ho — bien bien phuc tap", "Ghi chú 10 phuong tieu pho bien nhat Kim Quuy", "Bắt mạch + nhận định Phe/Vi khi Tan Dich"],
        ["On tuan 7-8 — Kim Quuy Yeu Luoc bien chung", "Viet 5 ca lam sang voi Kim Quuy phuong tieu", "Bắt mạch 5 người khac nhau"],
        ["Đọc Kim Quỹ: Bien chung khuong chuot lai benh — 4 loai", "Học 4 loại khuông chướng lai + phương thức", "Bắt mạch + nhận định am huong lai"],
        ["Đọc Kim Quỹ: Bien chung huyet chung — Giao Ai thang", "Học Giao Ngải thang + biến biến Can Huyết hư", "Bắt mạch + nhận định Can Tang"],
        ["Đọc Kim Quỹ: Ngu tang phong", "Học 5 dạng phong biểu hiện theo tạng", "Bắt mạch + nhận định tang bi anh huong"],
        ["Đọc Kim Quỹ: Ly huu (lien la lau ngay) — bien bien", "Phan biet han/nhiet/hu/thuc ly", "Bắt mạch + nhận định vi cuong yeu"],
        ["Đọc Kim Quỹ: O du, to, tri — bien bien ngo tang benh chu", "Ghi chú ngo tang benh chu bien bien", "Bắt mạch + phân tích 5 tang"],
        ["Đọc Kim Quỹ: Vong cu, bao bi thang", "Hoc cac phuong tieu Kim Quuy pho bien nhat", "Bắt mạch tổng hợp"],
        ["On tuan 9-10 — Kim Quuy toan tap", "Viet 10 ca lam sang ngan gon", "Bắt mạch tổng hợp + nhận định lâm sàng"],
        # Week 11-16: Thực hành biện chứng
        ["Thực hành biện chứng: Benh sot viem hong — Thai Duong hay Duong Minh?", "Phân tích qua mạch + triệu chứng", "Bắt mạch + chẩn đoán thử"],
        ["Thực hành biện chứng: Ho co dom vang — Tang nao?", "Biện biến Can Phế vs Vị nhiệt", "Bắt mạch + phác đồ thu"],
        ["Thực hành biện chứng: Met moi nguoi nha lam nhieu — Hu lao gi?", "Biện chứng Tỳ Khí hư vs Thận Âm hư", "Bắt mạch + phác đồ"],
        ["Thực hành biện chứng: Dau bung lanh, muon uong nuoc nong — Han hay Nhiet?", "Áp dụng Lý Trung biện chứng", "Bắt mạch Hoan Te hoac Te Tram"],
        ["Thực hành biện chứng: Moi kho khong muon uong — Tang nao?", "Biện chứng Âm hư vs Nhiệt hư", "Bắt mạch + ghi nhat ky"],
        ["Thực hành biện chứng: Them an nguot — Ty huu hay Vi nhiet?", "Phan tich Trung Tieu 3 tang", "Bắt mạch Quan 2 tay + nhan dinh"],
        ["On tuan 11-12 — bien chung thuc hanh", "Viet 6 ca lam sang hoan chinh", "Bắt mạch 6 nguoi"],
        ["Thực hành biện chứng: Dau dau sang khi thuc day — Am hay Duong?", "Phân tích Dương Khí và Nội Khí", "Bắt mạch buổi sáng sớm"],
        ["Thực hành biện chứng: Hoi hop, lo lang — Tang nao?", "Biện chứng Tâm Huyết vs Tâm Khí hư", "Bắt mạch Thon tay trai"],
        ["Thực hành biện chứng: Da kho bong tuoc — Phong hay Huyet kho?", "Biện chứng Can Huyết + Phong nội sinh", "Bắt mạch + nhận định Can khi"],
        ["Thực hành biện chứng: Mat ngu nhieu mo — Tam Tang hay Can Tang?", "Phan tich Tam Than + Can Hoa", "Bắt mạch + phác đồ"],
        ["Thực hành biện chứng: Tre em hay quoc khoc — Tang nao?", "Biện chứng trẻ em theo Thiếu Âm Quyết Âm", "Bắt mạch trẻ em (nếu có thể)"],
        ["On tuan 13-14 — bien chung phuc tap", "Viet 6 ca lam sang moi", "Bắt mạch + tổng kết"],
        # Week 15-20: Ky nang tong hop
        ["Biện biến Thiếu Dương phức hợp: Sai Ho + bien bien vao Tang", "Học 6 phương Sài Hồ biến biến", "Bắt mạch Huyen Khun"],
        ["Biện biến hạ pháp: Phu, Hoan, Viet — khi nao dung?", "Ghi chú 5 bien bien sau khi ha phap", "Bắt mạch + nhận định"],
        ["Biện biến Dương Minh và Thiếu Âm phức hợp: 3 am kep 2 duong", "Phan tich 6 phac do dac biet", "Bắt mạch + chẩn đoán"],
        ["Hoc phap do cho tremantle (phuong tieu co dieu chinh)", "Tong hop 10 phuong tieu hay bien doi nhat", "Bắt mạch + viet phac do thu"],
        ["On tuong tac thuoc: 18 phan, 19 ky, 6 co than", "Ghi chú cac cap thuoc khong ket hop", "Hiểu an toàn trước khi kê đơn"],
        ["Kết hợp Châm Cứu + Thương Hàn: khi nào thêm châm?", "Ghi chú 5 tình huống phát huy nhất", "Bắt mạch + phác đồ kết hợp"],
        ["On tuan 15-16 — nang cao", "Tự test 30 câu hỏi biện chứng", "Bắt mạch tổng hợp"],
        # Week 17-20: Chuan bi thi
        ["On thi: Thuong Han 6 kinh bien chung (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On thi: Phuong tieu Thuong Han 20 phuong quan trong (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On thi: Kim Quuy bien chung tap benh (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On thi: Tu Thanh Tam Nguyen + Duong Khi ly thuyet (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On lan 2: 6 kinh + phuong tieu", "Ghi chú diem yeu con lai", "Bắt mạch"],
        ["On lan 2: Kim Quuy + Ly luan nang cao", "Ghi chú diem yeu con lai", "Bắt mạch"],
        ["Nghi — thien + on nhe", "Viet nhat ky tu danh gia 224 ngay hoc", "Bắt mạch + nghỉ sớm"],
        ["On tong luc — tat ca diem yeu", "Lam 40 cau ngau nhien lan cuoi", "Bắt mạch"],
        ["Kiem tra bien chung thuc hanh: phan tich 3 ca lam sang", "Tu danh gia chinh xac bien chung", "Bắt mạch 3 ca"],
        ["Tổng ôn cuối — mỗi phần 30 phút", "Ghi chú tu tin vao tung phan", "Bắt mạch tổng hợp"],
        ["Nghi ngoi + chuan bi tam ly", "Ngu du giac, khong on khuya", "Bắt mạch buoi sang"],
        ["Ngày thi Phase 3 — bot sẽ gửi đề thi hôm nay", "Giu tam binh tinh, tin vao 224 ngay hoc", "Bắt mạch trước khi thi"],
    ] + [  # padding to 224
        [f"Ôn tập Thương Hàn ngày {i+1}", "Ghi chú 3 diem can on", "Bắt mạch + liên hệ lý thuyết"]
        for i in range(224 - 32*7)
    ],

    4: [  # Phase 4 — 20 weeks = 140 days — On Benh Hoc
        # Week 1 — On Benh Dieu Bien
        ["Đọc Ôn Bệnh Điều Biện: Mo dau, lich su On Benh hoc", "Ghi chú sự khác biệt Ôn Bệnh vs Thương Hàn", "Bắt mạch + nhận định Khi nhiet"],
        ["Đọc Ôn Bệnh Điều Biện: Ve Khi Dinh Huyet 4 tang co ban", "Ghi chú triệu chứng mỗi tầng", "Bắt mạch + phân loại tạng mạch đang ở"],
        ["Đọc Ôn Bệnh Điều Biện: Ve phan — Bieu phan nhiet chung", "Học Mạch Kinh — Ngân Kiều thang cho Vệ phần", "Bắt mạch Phu Sac — Ve phan"],
        ["Đọc Ôn Bệnh Điều Biện: Khi phan — Nhiet nap Duong Minh", "Học Bạch Hổ thang trong Ôn Bệnh", "Bắt mạch Sac Hoan Dai — Khi phan"],
        ["Đọc Ôn Bệnh Điều Biện: Dinh phan — nhiet nhap Dinh Khi", "Học Thanh Dinh thang — thanh nhiệt lương dinh", "Bắt mạch Sac Te — Dinh phan"],
        ["Đọc Ôn Bệnh Điều Biện: Huyet phan — nhiet doc thien huyet", "Học Tê Giác thang — lương huyết giải độc", "Bắt mạch Te Sac — Huyet phan"],
        ["On tuan 1 — Ve Khi Dinh Huyet co ban", "Vẽ sơ đồ 4 tầng Vệ Khí Dinh Huyết", "Bắt mạch tổng hợp + nhận định tạng"],
        # Week 2 — On Nhiet Luan (Diep Thien Si)
        ["Đọc Ôn Nhiệt Luận: Nhiet benh theo kinh mach", "So sanh On Nhiet vs Ve Khi Dinh Huyet cua Ngo Khuyen", "Bắt mạch + phân tích"],
        ["Đọc Ôn Nhiệt Luận: Ngu Phong Nhiet khi", "Học 5 loại phong nhiệt Diệp Thiên Sĩ", "Bắt mạch Phu Sac Hoan — phong nhiet"],
        ["Đọc Ôn Nhiệt Luận: Phuc nhiet, tro nhiet, tan nhiet", "Ghi chú các pháp thanh nhiệt Ôn Bệnh", "Bắt mạch + nhận định nhiet do"],
        ["Đọc Ôn Nhiệt Luận: Am huu trong On Benh — bao ve Am dich", "Học quy tắc bảo Âm trong bệnh nhiệt", "Bắt mạch + ghi nhat ky"],
        ["Tổng hợp Ôn Nhiệt Luận: 10 nguyên tắc trị nhiệt bệnh", "Viet 10 nguyen tac theo thu tu uu tien", "Bắt mạch + áp dụng nguyen tac"],
        ["So sanh On Nhiet Luan (Diep Thien Si) vs On Benh Dieu Bien (Ngo Khuyen)", "Ghi chú 5 điểm khác biệt chính", "Bắt mạch tổng hợp"],
        ["On tuan 2 — On Nhiet Luan toan bo", "Viết bài phân tích ngắn về phương pháp Diệp Thiên Sĩ", "Bắt mạch + cam nhan"],
        # Week 3 — Tam Tieu bien chung
        ["Đọc Ôn Bệnh Điều Biện: Thuong Tieu — Phe + Tam thanh nhiet", "Học Bạc Hà Nguyệt Sơn thang cho Phế Khí Nhiệt", "Bắt mạch Thon tay phai — Phe Nhiet"],
        ["Đọc Ôn Bệnh Điều Biện: Trung Tieu — Ty Vi nhiet Tan Dich", "Học Tăng Dịch thang cho Trung Tiêu Nhiệt", "Bắt mạch Quan tay phai — Vi Nhiet"],
        ["Đọc Ôn Bệnh Điều Biện: Ha Tieu — Than + Can am huu", "Học Gia Giảm Phục Mạch thang cho Hạ Tiêu Nhiệt", "Bắt mạch Xich tay trai — Than Am"],
        ["So sanh Ve Khi Dinh Huyet vs Tam Tieu bien chung", "Ghi chú khi nao dung phuong phap nao", "Bắt mạch + chẩn đoán theo 2 he"],
        ["Ung dung thuc te: benh nhiet do cao — Khi phan hay Dinh phan?", "Phân tích qua triệu chứng + mạch", "Bắt mạch + chẩn đoán thử"],
        ["Ung dung thuc te: sot 5 ngay khong ha — Diep Thien Si phap", "Ap dung On Nhiet Luan cho truong hop phuc tap", "Bắt mạch + phác đồ"],
        ["On tuan 3 — Tam Tieu bien chung + ung dung", "Viet 3 ca lam sang theo 2 he thong", "Bắt mạch 3 người"],
        # Week 4 — On Benh dac biet va tap chung
        ["Đọc Ôn Bệnh Điều Biện: On Dich (dich benh)", "Ghi chú đặc điểm bệnh dịch vs thường nhiệt", "Bắt mạch + nhận định doc khi"],
        ["Đọc Ôn Bệnh Điều Biện: Shu Wen dich On — Thanh Wen Bai Du thang", "Học phương thức điều trị Ôn Dịch", "Ghi chú lịch sử Ôn Dịch Trung Quốc"],
        ["Đọc Ôn Bệnh Điều Biện: Phu tu On (On benh o phu nu co thai)", "Học biến biến đặc biệt phụ từ Ôn", "Bắt mạch phụ nữ + nhận định"],
        ["Đọc Ôn Bệnh Điều Biện: Nhu Ngo (buon ngu qua muc o On benh)", "Ghi chú cơ chế Tâm Khí bị ẩn", "Bắt mạch + nhận định Tam Khi"],
        ["Tong hop: 6 chung tap cua On Benh hoc can biet", "Viet bang tom tat bien chung ↔ phuong tieu", "Bắt mạch + áp dụng"],
        ["Đọc Ôn Nhiệt Luận (tiep tuc): Xu ly nhiet nhap Tam Bao", "Học Ngưu Hoàng Tán và Thanh Cung thang", "Bắt mạch Te Sac — Huyet phan, Tam Bao"],
        ["On tuan 4 — On Dich + tap chung + Tam Bao nhiet", "Viet 5 ca lam sang On Benh", "Bắt mạch tổng hợp"],
        # Week 5-8: Thuc hanh va tong hop
        ["So sanh Thuc hanh: Thuong Han vs On Benh — khi nao dung cai nao?", "Ghi chú 10 tieu chi phan biet", "Bắt mạch + chuyển hướng biện chứng"],
        ["Kết hợp Thương Hàn + Ôn Bệnh trong 1 ca lâm sàng phức tạp", "Viết ca lâm sàng phức tạp 2 hệ thống", "Bắt mạch + phác đồ kết hợp"],
        ["Phan tich: benh sot xuat huyet theo On Benh hoc", "Ap dung Ve Khi Dinh Huyet phan tich tu ca", "Bắt mạch + nhận định giai doan"],
        ["Phan tich: viem phoi COVID-19 theo On Benh hoc", "Ap dung Tam Tieu bien chung cho benh phoi", "Ghi chú: On Benh hoc va benh hien dai"],
        ["Phan tich: sot rot (malaria) qua On Benh hoc", "Học Triệt Ngược thang cho sốt lại hai ngày", "Bắt mạch Huyen — Can Khi ung phuc"],
        ["Phan tich: liem tiep tuc (Typhoid) qua On Benh hoc", "Ap dung Dinh Khi nhiet cho benh tieu hoa nang", "Bắt mạch Sac Te — giai doan nang"],
        ["On tuan 5-6 — so sanh Thuong Han + On Benh", "Viết 3 ca lâm sàng theo hệ thống chọn phương pháp", "Bắt mạch tổng hợp"],
        # Week 7
        ["Hoc Mo Nguyen (bao gom On Benh qua khuong chuot lai)", "Ghi chú ôn bệnh mùa đông qua xuân", "Bắt mạch Huyen Phu — mo nguyen"],
        ["Hoc Thap On (On Benh ket hop voi Thap tac nhan)", "Phan biet On Benh thuan tuy vs co Thap", "Bắt mạch Hoan Te — Thap On"],
        ["Hoc Tri On (khi am chet benh lat cat)", "Ghi chú đặc điểm bệnh Trị Ôn", "Bắt mạch Sac Khun"],
        ["Hoc Shu Wen 2: bien bien On Dich khang thuoc", "Phân tích: tại sao Ôn Dịch khó trị?", "Ghi chú lịch sử Ôn Dịch và kiến giải"],
        ["Tổng hợp 6 loại Ôn Bệnh đặc biệt", "Vẽ bảng phân loại Ôn Bệnh đầy đủ", "Bắt mạch + phan biet tung loai"],
        ["Phuong tieu On Benh: 15 phuong co ban nhat", "Lam bang flashcard 15 phuong", "Bắt mạch + chỉ định thử"],
        ["On tuan 7 — On Benh dac biet", "Tự test 10 câu hỏi Ôn Bệnh đặc biệt", "Bắt mạch tổng hợp"],
        # Week 8-10: Tong hop chuyen sau
        ["On Benh hoc hien dai: ung dung trong benh truyen nhiem", "Ghi chú 5 bệnh truyền nhiễm có thể dùng Ôn Bệnh", "Bắt mạch"],
        ["Kết hợp Ôn Bệnh và Phế Khí: ARDS qua góc nhìn Đông y", "Phân tích Phế Khí cự tuyệt trong Ôn Bệnh", "Bắt mạch + nhận định Phe"],
        ["Kết hợp Ôn Bệnh và septic shock: Âm hư + Dương thoát", "Phân tích hôn mê sep qua Ôn Bệnh", "Bắt mạch Te Sac Vo Luc — Am Duong thoat"],
        ["Phân tích: Pháp trị trong Ôn Bệnh — Phát Hàn, Hạ, Thanh, Tư", "Ghi chú khi nào dùng pháp gì", "Bắt mạch + quyết định pháp trị"],
        ["Ứng dụng bài thuốc Ôn Bệnh trong bài thuốc hiện đại", "Ghi chú 5 bài thuốc Ôn Bệnh đã được nghiên cứu hiện đại", "Bắt mạch + ghi nhat ky"],
        ["Kết hợp Châm Cứu với Ôn Bệnh: tăng cường âm khi nhiệt bệnh", "Ghi chú 5 huyệt quan trọng trong Ôn Bệnh", "Bấm nhẹ Nội Quan + Tam Âm Giao"],
        ["On tuan 8-10 — On Benh hien dai + ket hop", "Viet 5 ca lam sang phuc tap ket hop", "Bắt mạch 5 người"],
        # Week 11-14: Chuan bi thi
        ["On thi: Ve Khi Dinh Huyet 4 tang (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On thi: On Nhiet Luan — Diep Thien Si (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On thi: Tam Tieu bien chung On Benh (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On thi: On Benh dac biet + ung dung lam sang (40 cau)", "Làm chắc", "Bắt mạch"],
        ["On lan 2: Ve Khi Dinh Huyet + On Nhiet Luan", "Ghi chú diem yeu con lai", "Bắt mạch"],
        ["On lan 2: Tam Tieu bien chung + On Benh dac biet", "Ghi chú diem yeu con lai", "Bắt mạch"],
        ["Nghi — thien + on nhe", "Viet nhat ky hanh trinh 560+ ngay hoc Dong y", "Bắt mạch + nghỉ sớm"],
        # Week 15
        ["On tong luc — tat ca diem yeu On Benh", "Lam 40 cau ngau nhien lan cuoi", "Bắt mạch"],
        ["Kiem tra tong hop: bien chung 3 ca lam sang On Benh", "Tu danh gia chinh xac", "Bắt mạch 3 ca"],
        ["Tong on cuoi: Ve Khi Dinh Huyet + Tam Tieu + 15 phuong co ban", "Doc nhanh, danh dau diem cot yeu", "Bắt mạch tổng hợp"],
        ["Nghi ngoi + chuan bi tam ly", "Ngu du giac, khong on khuya", "Bắt mạch buoi sang"],
        ["Ngày thi Phase 4 — bot sẽ gửi đề thi hôm nay", "Giu tam binh tinh, tin vao 140 ngay On Benh", "Bắt mạch trước khi thi"],
    ] + [  # padding to 140
        [f"Ôn tập Ôn Bệnh ngày {i+1}", "Ghi chú 3 diem can on", "Bắt mạch + liên hệ lý thuyết"]
        for i in range(140 - 20*7)
    ],
}

# Trim or validate counts
for _ph in [2, 3, 4]:
    target = {2: 140, 3: 224, 4: 140}[_ph]
    if len(CURRICULUM[_ph]) > target:
        CURRICULUM[_ph] = CURRICULUM[_ph][:target]
    while len(CURRICULUM[_ph]) < target:
        n = len(CURRICULUM[_ph]) + 1
        CURRICULUM[_ph].append([f"Ôn tập Phase {_ph} ngay {n}", "Ghi chú 3 diem can on", "Bắt mạch + liên hệ lý thuyết"])
