# -*- coding: utf-8 -*-
# Each phase has weeks, each week has 7 days, each day has 3-4 tasks

CURRICULUM = {
    0: [  # Phase 0 — 8 weeks = 56 days — Noi Kinh Nen Tang
        # Week 1
        ["Doc To Van Chuong 1: Thuong Co Thien Chan Luan", "Ghi chu 3 khai niem Am Duong", "Bat mach tay trai 5 phut"],
        ["Doc To Van Chuong 2: Tu Khi Dieu Than Luan", "Ve so do 4 mua <-> Tang Phu", "Bat mach so sanh sang/toi"],
        ["Doc To Van Chuong 3: Sinh Khi Thong Thien Luan", "Ghi chu ve Duong Khi va benh ly", "Quan sat luoi nguoi than"],
        ["Doc To Van Chuong 4: Kim Quy Chan Ngon Luan", "Hoc thuoc Ngu Hanh tuong sinh", "Bat mach 10 phut"],
        ["Doc To Van Chuong 5: Am Duong Ung Tuong Dai Luan (phan 1)", "Ghi chu 5 am 5 vi 5 sac", "Tu kiem tra Ngu Hanh tuong khac"],
        ["Doc To Van Chuong 5: Am Duong Ung Tuong Dai Luan (phan 2)", "Ve bang Ngu Hanh day du", "Bat mach + ghi nhat ky"],
        ["On lai tuan 1 — To Van Chuong 1-5", "Tra loi: Duong Khi co vai tro gi trong bao ve co the?", "Nghi ngoi, khong bat mach"],
        # Week 2
        ["Doc To Van Chuong 6: Am Duong Ly Hop Luan", "Ghi chu 3 am 3 duong kinh", "Bat mach + phan biet Phu/Tram"],
        ["Doc To Van Chuong 8: Linh Lan Bi Dien Luan — Tang Phu chuc nang", "Thuoc chuc nang 5 tang", "Quan sat mau sac mat nguoi than"],
        ["Doc To Van Chuong 9: Luc Tiet Tang Tuong Luan", "Ghi chu Tang Tuong hoc", "Bat mach 15 phut"],
        ["Doc To Van Chuong 10: Ngu Tang Sinh Thanh", "Ve so do Ngu Tang quan he", "Tu hoi: Than tang gi?"],
        ["Doc To Van Chuong 11: Ngu Tang Biet Luan", "Phan biet Tang vs Phu chuc nang", "Bat mach + ghi nhat ky"],
        ["Bat dau Linh Khu Chuong 1: Cuu Cham Thap Nhi Nguyen", "Ghi chu 12 huyet Nguyen", "Bat mach tay phai"],
        ["On lai tuan 2 — Tang Phu chuc nang", "Tra loi: Su khac nhau giua Tang va Phu?", "Bat mach + so sanh voi tuan truoc"],
        # Week 3
        ["Doc Linh Khu Chuong 8: Ban Than", "Ghi chu Than/Hon/Phach/Y/Chi", "Thien 10 phut, quan sat Khi"],
        ["Doc Linh Khu Chuong 10: Kinh Mach — Kinh Thu Thai Am Phe", "Ve duong kinh Phe", "Bat mach vi tri Thon tay phai"],
        ["Doc Linh Khu Chuong 10 — Kinh Thu Duong Minh Dai Truong", "Ve duong kinh Dai Truong", "Bat mach 15 phut"],
        ["Doc Linh Khu Chuong 10 — Kinh Tuc Duong Minh Vi + Tuc Thai Am Ty", "Ve 2 duong kinh", "Bat mach + ghi nhat ky"],
        ["Doc Linh Khu Chuong 10 — Kinh Thu Thieu Am Tam + Thu Thai Duong Tieu Truong", "Ve 2 duong kinh", "Quan sat sac mat + luoi"],
        ["Doc Linh Khu Chuong 10 — Kinh Tuc Thai Duong Bang Quang + Tuc Thieu Am Than", "Ve 2 duong kinh", "Bat mach Xich tay trai (Than)"],
        ["On 6 kinh dau — ve lai tu tri nho", "Tra loi: Kinh nao di qua mat?", "Bat mach + so sanh Thon/Quan/Xich"],
        # Week 4
        ["Doc Linh Khu Chuong 10 — Kinh Thu Quyet Am Tam Bao + Thu Thieu Duong Tam Tieu", "Ve 2 duong kinh", "Bat mach"],
        ["Doc Linh Khu Chuong 10 — Kinh Tuc Thieu Duong Dom + Tuc Quyet Am Can", "Ve 2 duong kinh", "Bat mach Quan tay trai (Can)"],
        ["Doc Linh Khu Chuong 10 — Mach Doc + Mach Nham", "Ve 2 mach ky", "Thien 15 phut cam nhan truc Nham-Doc"],
        ["Doc Bat Thap Nhat Nan Kinh: Nan 1-10 (mach hoc)", "Ghi chu: mach binh thuong la gi?", "Bat mach + ghi so nhip/phut"],
        ["Doc Nan Kinh: Nan 11-22 (mach benh ly)", "Ghi chu 5 loai mach chet", "Bat mach nguoi than"],
        ["Doc Nan Kinh: Nan 23-29 (kinh mach)", "So sanh voi Linh Khu Chuong 10", "Bat mach + ghi nhat ky"],
        ["On lai tuan 4 — 12 kinh + Nan Kinh", "Ve vong luu chu 12 kinh tu tri nho", "Bat mach tong hop"],
        # Week 5
        ["Doc Y Hoc Tam Tu Kinh: Phan Y Hoc Nguyen Luu", "Ghi chu lich su y hoc tu Than Nong den Truong Trong Canh", "Bat mach"],
        ["Doc Y Hoc Tam Tu Kinh: Phan Am Duong", "So sanh voi Noi Kinh da hoc", "Quan sat luoi + ghi chu"],
        ["Doc Y Hoc Tam Tu Kinh: Phan Tang Phu", "Kiem tra lai kien thuc tang phu", "Bat mach + nhan xet"],
        ["Doc Y Hoc Tam Tu Kinh: Phan Kinh Lac", "So sanh voi Linh Khu", "Bat mach 20 phut"],
        ["Doc To Van Chuong 17: Mach Yeu Tinh Vi Luan", "Ghi chu tu mua mach tuong", "Bat mach sang + toi"],
        ["Doc To Van Chuong 18: Binh Nhan Khi Tuong Luan", "Hoc mach binh thuong theo mua", "Bat mach + so sanh ly thuyet"],
        ["On tuan 5 — Y Hoc Tam Tu Kinh + mach theo mua", "Tra loi: Mach mua xuan dac diem gi?", "Bat mach tong hop"],
        # Week 6
        ["Doc To Van Chuong 19: Ngoc Co Chan Tang Luan — mach chan tang", "Ghi chu 5 mach chan tang", "Bat mach 20 phut"],
        ["Doc Nan Kinh: Nan 30-47 (Tang Phu chuyen sau)", "Ghi chu diem khac vs Noi Kinh", "Quan sat luoi + mat"],
        ["Doc Nan Kinh: Nan 48-61 (benh ly)", "Ghi chu phan biet hu/thuc", "Bat mach + nhan dinh hu/thuc"],
        ["Doc Nan Kinh: Nan 62-68 (huyet dac biet)", "Ghi chu Ngu du huyet ly luan", "Bat mach + ghi nhat ky"],
        ["Doc Nan Kinh: Nan 69-81 (tri tac)", "Ghi chu nguyen tac bo ta", "Bat mach nguoi than + nhan dinh"],
        ["On Nan Kinh toan bo", "Tom tat 10 diem quan trong nhat", "Bat mach tong hop"],
        ["Nghi on tap — khong doc sach moi", "Viet lai tu tri nho: 5 chuc nang Tang Phe", "Thien + cam nhan Khi"],
        # Week 7
        ["On tong hop: Am Duong Ngu Hanh", "Tra loi 10 cau hoi tu dat", "Bat mach + ghi"],
        ["On tong hop: Tang Phu chuc nang", "Ve bang Tang-Phu-Kinh-Sac-Vi-Am", "Bat mach"],
        ["On tong hop: 12 Kinh chinh + Ky Kinh", "Ve vong luu chu tu tri nho", "Bat mach + so sanh voi tuan 1"],
        ["On tong hop: Khi Huyet Tan Dich", "Giai thich Nguyen Khi/Tong Khi/Dinh Khi/Ve Khi", "Bat mach"],
        ["On tong hop: Nan Kinh diem dac thu", "So sanh 5 diem Nan Kinh khac Noi Kinh", "Bat mach"],
        ["Doc lai Noi Kinh To Van Chuong 1 — nhin voi con mat moi", "Ghi nhan thay doi trong hieu biet", "Bat mach + ghi nhat ky"],
        ["Chuan bi thi Phase 0 — on 160 cau trac nghiem", "Tu hoi 20 cau ngau nhien", "Nghi ngoi"],
        # Week 8
        ["On thi: Am Duong (25 cau dau)", "Ghi chu diem yeu", "Bat mach"],
        ["On thi: Ngu Hanh (25 cau)", "Ghi chu diem yeu", "Bat mach"],
        ["On thi: Ngu Tang (30 cau)", "Ghi chu diem yeu", "Bat mach"],
        ["On thi: Luc Phu + Khi Huyet (40 cau)", "Ghi chu diem yeu", "Bat mach"],
        ["On thi: Kinh Lac + Nan Kinh (40 cau)", "Ghi chu diem yeu", "Bat mach"],
        ["On tong luc — lam lai tat ca diem yeu", "Nghi som, ngu du giac", "Bat mach nhe"],
        ["Ngay thi Phase 0 — bot se gui de thi hom nay", "Giu tam binh tinh", "Bat mach truoc khi thi"],
    ],

    1: [  # Phase 1 — 12 weeks = 84 days — Mach Hoc
        # Week 1 — 6 mach co ban
        ["Doc Mach Kinh Quyen 1: Mach hinh 24 loai — Tong quan", "Hoc mach Phu — cam giac nhe noi tren mat da", "Bat mach 20 phut, tim mach Phu"],
        ["Doc Mach Kinh: Mach Tram — cam giac nang sau", "So sanh Phu vs Tram tren cung nguoi", "Bat mach nguoi than"],
        ["Doc Mach Kinh: Mach Tri (cham <4 nhip/ho hap)", "Dem nhip mach tay trai 1 phut", "Bat mach nguoi cao tuoi neu co"],
        ["Doc Mach Kinh: Mach Sac (nhanh >5 nhip/ho hap)", "So sanh Tri vs Sac", "Bat mach sau van dong nhe"],
        ["Doc Mach Kinh: Mach Hu va Mach Thuc", "Cam nhan luc cua mach", "Bat mach + ghi luc (1-5)"],
        ["Doc Mach Kinh: Mach Hoat — tron tru nhu hat chau", "Tap nhan biet Hoat vs Sap", "Bat mach phu nu tre"],
        ["On 6 mach dau: Phu/Tram/Tri/Sac/Hu/Thuc/Hoat", "Tu mo ta lai tung mach bang loi", "Bat mach tong hop"],
        # Week 2
        ["Doc Mach Kinh: Mach Sap — tho rap khong tron", "So sanh Hoat vs Sap", "Bat mach nguoi met moi"],
        ["Doc Mach Kinh: Mach Hong — to rong nhu song bien", "Tim mach Hong trong mua ha", "Bat mach + ghi bien do"],
        ["Doc Mach Kinh: Mach Te — nho nhu soi chi", "So sanh Hong vs Te", "Bat mach nguoi gay"],
        ["Doc Mach Kinh: Mach Huyen — thang nhu day dan", "Tim mach Huyen o Can/Dom", "Bat mach Quan tay trai"],
        ["Doc Mach Kinh: Mach Khan — cang nhu day thua", "So sanh Huyen vs Khan", "Bat mach nguoi dau"],
        ["Doc Mach Kinh: Mach Hoan — cham deu nhu mua thu", "Phan biet Hoan binh thuong vs benh ly", "Bat mach sau bua an"],
        ["On mach Sap/Hong/Te/Huyen/Khan/Hoan", "Tu test: bat mach va doan loai mach", "Bat mach 5 nguoi"],
        # Week 3
        ["Doc Mach Kinh: Mach Truong — truot dai qua 3 vi tri", "So sanh Truong vs Hoan", "Bat mach + ghi do dai"],
        ["Doc Mach Kinh: Mach Doan — khong du toi Quan hoac Xich", "Phan biet Truong vs Doan", "Bat mach nguoi benh yeu"],
        ["Doc Mach Kinh: Mach Chuyen — mach tron xoay nhu day thua", "Tap nhan biet Chuyen", "Bat mach nguoi dau bung"],
        ["Doc Mach Kinh: Mach Dong — mach roi loan, giat cum", "Ghi chu bieu hien lam sang", "Bat mach nguoi hoi hop lo lang"],
        ["Doc Mach Kinh: Mach Lac — tu ngung roi tiep tuc deu", "Phan biet cac mach gian doan", "Bat mach nguoi trung nien"],
        ["Doc Mach Kinh: Mach Dai — tu ngung khong deu, lau phuc lai", "So sanh Lac vs Dai vs Ket", "Bat mach ky can than"],
        ["On tong tat 24 mach — tu test toan bo", "Ve bang phan loai 24 mach theo am/duong", "Bat mach 10 nguoi khac nhau"],
        # Week 4 — Mach theo tang phu
        ["Doc Mach Kinh Quyen 2: Mach theo Tang Phu — Tam Phe vi Thon", "Hoc vi tri 3 ngon tay Thon/Quan/Xich", "Bat mach phan biet ro 3 vi"],
        ["Mach Ty Vi ung voi Quan tay phai", "Ghi chu mach binh thuong Ty Vi theo mua", "Bat mach sau bua an so sanh"],
        ["Mach Than Menh Mon ung Xich tay phai", "Ghi chu mach Thuong Han Luan ve Than", "Bat mach Xich tay phai + ghi"],
        ["Mach Can Dom ung Quan tay trai", "Hoc mach Huyen o Quan — bieu hien Can khi ult", "Bat mach buoi sang som"],
        ["Mach Than Bang Quang ung Xich tay trai", "So sanh mach Than 2 tay", "Bat mach nguoi nhieu tuoi"],
        ["Tong hop mach 6 vi tri — tu test khong nhin sach", "Ghi chu 3 nguoi vua bat mach + nhan dinh", "Bat mach + viet nhat ky mach"],
        ["On tuan 4 — mach tang phu 6 vi", "Tra loi: Mach Ty binh thuong khac Ty huu nhu the nao?", "Bat mach tong hop"],
        # Week 5 — Nan Kinh mach hoc
        ["Doc Nan Kinh Nan 1-5: Thuoc mach, do dai, so nhip", "Ghi chu dinh nghia mach binh thuong Nan Kinh", "Bat mach dem chinh xac nhip"],
        ["Doc Nan Kinh Nan 6-10: Am duong mach, Phuc mach, Phu mach", "So sanh voi Mach Kinh", "Bat mach nguoi met sau lam viec"],
        ["Doc Nan Kinh Nan 11-15: Mach co vat, mach that, thay doi theo mua", "Ghi chu mach tu mua", "Bat mach + doan mua hien tai"],
        ["Doc Nan Kinh Nan 16-20: Mach tang + benh chung tuong ung", "Phan tich 5 loai mach benh ly", "Bat mach nguoi co benh man tinh"],
        ["Doc Nan Kinh Nan 21-22: Mach hinh vs mach khi", "Ghi chu phan biet hinh vs khi", "Bat mach 3 nguoi + ghi hinh/khi"],
        ["Chan Mac Yeu Quyet — toan bo (sach mong)", "Ghi chu 10 diem Chan Mac Yeu Quyet khac Mach Kinh", "Bat mach + ap dung Chan Mac"],
        ["On tuan 5 — Nan Kinh mach hoc", "Tu dat 10 cau hoi ve mach hoc", "Bat mach + tra loi cac cau"],
        # Week 6 — Mach va lam sang
        ["Mach va benh Phong Han: Phu Khuan, Phu Sac, Phu Nhuoc", "Ghi chu phan biet Phong Han Tuong", "Bat mach khi troi lanh"],
        ["Mach va benh Nhiet: Sac Dai, Sac Hua, Hong Te", "Ghi chu mach Nhiet chung", "Bat mach sau viec nang"],
        ["Mach va benh Hu Lao: Te Nhuoc, Tram Te, Tu Tri", "Phan tich ngu lao that thuong", "Bat mach nguoi lam viec nhieu"],
        ["Mach va am uong: Hoat Thuc, Hoan Thai, Tram Hong", "Ghi chu mach thuc tich", "Bat mach 1h sau an com"],
        ["Mach va cam xuc: Huyen Khuan, Hong Dai, Tram Khan", "Lien he Can khi, Tam than, Phoi buon", "Bat mach khi stress"],
        ["Mach va xuat huyet: Sac/Nhuoc/Te/Khong Phu", "Hoc mach thiet hiet tu can", "Bat mach + ghi nhat ky chi tiet"],
        ["On tuan 6 — mach lam sang", "Viet 3 ca lam sang tu kien/tue/kinh nghiem", "Bat mach tong hop"],
        # Week 7 — Mach kho va dac biet
        ["Mach that 7 loai — Bi Hu Tuyet, Que, Quach, Tan, Giai, Pha, Tuong", "Ghi chu y nghia tung mach", "Hieu chi, khong tap bat"],
        ["Mach Bat Tuong: 8 mach ky kinh va mach tuong ung", "Ve so do mach bat tuong", "Bat mach + tim dac diem ky kinh"],
        ["Mach Thai Ky (mach thai san)", "Ghi chu dac diem mach phu nu co thai", "Bat mach phu nu neu co the"],
        ["Mach Lao (mach nguoi cao tuoi)", "Phan biet mach lao binh thuong vs benh ly", "Bat mach nguoi tren 60"],
        ["Mach Xuat Huyet nao — nhan biet cap cuu", "Ghi chu 3 mach canh bao nguy hiem", "Hieu ly thuyet, khong thuc hanh cap cuu"],
        ["On mach kho va dac biet", "Tom tat bang phan loai mach theo muc do nghiem trong", "Bat mach tong hop + ghi danh gia"],
        ["Tu test: mo ta mach khong nhin sach", "Mo ta bang loi 10 loai mach ngau nhien", "Bat mach va doan chuan xac"],
        # Week 8 — Thuc hanh chuyen sau
        ["Bat mach buoi sang: ghi nhip, luc, do sau, hinh thai", "Nhat ky mach hoc: ghi day du 4 thong so", "Phan tich tu mach ban than"],
        ["Bat mach buoi toi: so sanh voi sang", "Ghi chu su thay doi trong ngay", "Phan tich nguyen nhan thay doi"],
        ["Bat mach sau khi uong ca phe/tra", "Ghi chu anh huong Thuc chat len mach", "Lien he ly thuyet Khi hoa"],
        ["Bat mach sau tap the duc 30 phut", "Ghi chu thay doi mach post-exercise", "Lien he Duong Khi van dong"],
        ["Bat mach truoc va sau an trua", "Ghi chu tac dong Ty Vi len mach", "Phan tich: co dung ly thuyet khong?"],
        ["Bat mach trong cac trang thai cam xuc khac nhau", "Ghi chu Can khi vs Tam than tren mach", "Viet nhat ky phan tich"],
        ["On tuan 8 — nhat ky mach hoc 7 ngay", "Tim quy luat ca nhan tu nhat ky mach", "Bat mach + ghi tong ket"],
        # Week 9 — Ket hop ly thuyet
        ["Doc lai Mach Kinh Quyen 3: Bien chung mach benh ly", "Ghi chu 10 bien chung quan trong", "Bat mach + ap dung bien chung"],
        ["Tong hop: mach Phu Tang benh ly", "Ve bang mach <-> chung tuong ung", "Bat mach + nhan dinh tang bi anh huong"],
        ["Tong hop: mach Phong Han Nhiet Thap", "Phan biet 4 ngoai tac qua mach", "Bat mach vao cac thoi diem khac nhau"],
        ["Tong hop: mach Khi Huyet Am Duong xu", "Ghi chu quy tac phan biet", "Bat mach 5 nguoi + nhan dinh"],
        ["Doc Nan Kinh Nan 1-22 lan 2 — doc lai voi mat mach hoc", "Ghi chu diem moi phat hien", "Bat mach + ung dung Nan Kinh"],
        ["So sanh Mach Kinh vs Nan Kinh: 5 diem khac biet chinh", "Viet bai phan tich ngan", "Bat mach + ghi nhat ky"],
        ["On tuan 9 — ly thuyet ket hop", "Tu test 20 cau hoi tong hop", "Bat mach tong hop"],
        # Week 10 — Chuan bi thi
        ["On mach 24 loai — mo ta va nhan biet", "Lam flashcard 24 mach", "Bat mach + test flashcard"],
        ["On mach theo tang phu 6 vi", "Ve lai tu tri nho ban do mach 6 vi", "Bat mach 3 nguoi + ghi nhan dinh"],
        ["On Nan Kinh mach hoc Nan 1-22", "Tom tat 22 nan thanh 1 trang", "Bat mach + ap dung"],
        ["On mach lam sang 6 chu de", "Viet 5 ca lam sang ngan", "Bat mach + chuan doan thu"],
        ["On mach kho va dac biet", "Kiem tra lai cac diem yeu", "Bat mach tong hop"],
        ["Lam de thi thu 80 cau mach hoc", "Ghi chu cac cau sai", "Bat mach + ghi ket qua"],
        ["On lai cac cau sai — phan tich nguyen nhan", "Hieu sau tung cau sai", "Bat mach + nghi som"],
        # Week 11
        ["Kiem tra toan dien mach hoc — 160 cau tu trac nghiem", "Ghi chu diem yeu con lai", "Bat mach tong hop"],
        ["On nhom 1: Am Duong mach (40 cau)", "Lam chac", "Bat mach"],
        ["On nhom 2: Mach Tang Phu (40 cau)", "Lam chac", "Bat mach"],
        ["On nhom 3: Mach benh ly (40 cau)", "Lam chac", "Bat mach"],
        ["On nhom 4: Nan Kinh mach hoc (40 cau)", "Lam chac", "Bat mach"],
        ["On tong luc — tat ca diem yeu", "Nghi som, ngu du giac", "Bat mach nhe"],
        ["Nghi — khong hoc moi", "Thien 20 phut, toan than thu gian", "Cam nhan mach chinh minh"],
        # Week 12
        ["On cuoi: Mach Kinh Quyen 1 + 2 + 3 toan bo", "Doc nhanh, danh dau diem cot yeu", "Bat mach"],
        ["On cuoi: Nan Kinh Nan 1-22 + Chan Mac Yeu Quyet", "Tom tat 1 trang moi sach", "Bat mach"],
        ["On cuoi: Mach lam sang + ca lam sang", "Viet 3 ca lam sang moi tu kinh nghiem", "Bat mach nguoi than"],
        ["On cuoi: Mach kho + mach dac biet", "Kiem tra lai lan cuoi", "Bat mach + danh gia ban than"],
        ["Tong on — lam 40 cau ngau nhien", "Chua sai, ghi chu cuoi cung", "Bat mach + cam on cuoc hanh trinh"],
        ["Nghi ngoi va on nhe", "Nghi som, thu gian tam ly", "Bat mach 10 phut nhe nhang"],
        ["Ngay thi Phase 1 — bot se gui de thi hom nay", "Giu tam binh tinh, tin vao thuc hanh 84 ngay", "Bat mach truoc khi thi"],
    ],

    2: [  # Phase 2 — 20 weeks = 140 days — Cham Cuu Chuyen Sau
        # Week 1 — Cham Cuu Dai Thanh Q1: 14 kinh chinh huyet vi
        ["Doc Cham Cuu Dai Thanh Q1: Mo dau, lich su cham cuu", "Ghi chu 10 moc lich su cham cuu quan trong", "Bat mach + lien he kinh mach"],
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Thu Thai Am Phe — 11 huyet", "Ve duong kinh Phe + ghi ten 11 huyet", "Tim vi tri Trung Phu, Vun Mon tren co the"],
        ["Hoc vi tri 11 huyet kinh Phe tren co the", "Ghi chu chi dinh dieu tri cua moi huyet", "Tap bam diem xac dinh vi tri huyet"],
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Thu Duong Minh Dai Truong — 20 huyet", "Ve duong kinh + 20 huyet", "Tim Hop Coc, Khuc Tri tren tay"],
        ["Hoc vi tri 20 huyet kinh Dai Truong", "Ghi chu chi dinh dieu tri", "Bam Hop Coc — cam nhan Dac Khi"],
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Tuc Duong Minh Vi — 45 huyet", "Ve duong kinh Vi + 45 huyet", "Tim Tuc Tam Ly, Phong Long tren chan"],
        ["On tuan 1 — 3 kinh dau (Phe/Dai Truong/Vi)", "Ve lai tu tri nho, ghi diem quan trong nhat", "Bat mach + lien he 3 kinh"],
        # Week 2
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Tuc Thai Am Ty — 21 huyet", "Ve duong kinh Ty + 21 huyet", "Tim Tam Am Giao, Hoan Khe"],
        ["Hoc vi tri huyet Tam Am Giao, Dia Co, Hoan Khe, Huynh Mon, Dai Bao", "Ghi chu chi dinh cua tung huyet", "Bam Tam Am Giao — ghi cam nhan"],
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Thu Thieu Am Tam — 9 huyet", "Ve duong kinh Tam + 9 huyet", "Tim Tam kinh tren tay"],
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Thu Thai Duong Tieu Truong — 19 huyet", "Ve duong kinh + 19 huyet", "Tim Thieu Trach, Hau Khe"],
        ["Hoc vi tri 9 huyet Tam + 19 huyet Tieu Truong quan trong nhat", "Ghi chu chi dinh dieu tri", "Bam diem + ghi cam nhan"],
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Tuc Thai Duong Bang Quang — 67 huyet", "Ve duong kinh + ghi ten 67 huyet", "Tim Du Huyyet cua cac tang"],
        ["On tuan 2 — Ty/Tam/Tieu Truong/Bang Quang", "Ve lai tu tri nho 4 kinh", "Bat mach + lien he 4 kinh vua hoc"],
        # Week 3
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Tuc Thieu Am Than — 27 huyet", "Ve duong kinh Than + 27 huyet", "Tim Duong Tuyen, Phuc Luu tren chan"],
        ["Hoc Vi Du, Can Du, Phe Du, Tam Du, Than Du — ngu tang du huyet", "Ghi chu chi dinh tung Du huyet", "Bam nhe Du huyet tren lung"],
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Thu Quyet Am Tam Bao — 9 huyet", "Ve duong kinh Tam Bao + 9 huyet", "Tim Lao Cung, Noi Quan"],
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Thu Thieu Duong Tam Tieu — 23 huyet", "Ve duong kinh Tam Tieu + 23 huyet", "Tim Ngoai Quan, Dan Trung huyet"],
        ["Hoc vi tri Noi Quan, Ngoai Quan — cap huyet doi nhau", "Ghi chu so sanh chi dinh 2 huyet", "Bam Noi Quan + Ngoai Quan"],
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Tuc Thieu Duong Dom — 44 huyet", "Ve duong kinh Dom + 44 huyet", "Tim Phong Thi, Dich Truyen, Duong Lang Tuyen"],
        ["On tuan 3 — Than/Tam Bao/Tam Tieu/Dom", "Ve lai tu tri nho 4 kinh moi", "Bat mach + nhan dinh luc phf tang hom nay"],
        # Week 4
        ["Doc Cham Cuu Dai Thanh Q1: Kinh Tuc Quyet Am Can — 14 huyet", "Ve duong kinh Can + 14 huyet", "Tim Thai Xung, Hanh Gian"],
        ["Doc Cham Cuu Dai Thanh Q1: Mach Doc — 28 huyet", "Ve Mach Doc tu Truong Cuong len Nguyen Hoi", "Tim Bach Hoi, Phong Phu, Nhan Trung"],
        ["Doc Cham Cuu Dai Thanh Q1: Mach Nham — 24 huyet", "Ve Mach Nham tu Hoi Am len Thua Tuong", "Tim Quan Nguyen, Khi Hai, Trung Wan"],
        ["Hoc 8 Ky Kinh: ten va duong di co ban", "Ve so do 8 ky kinh don gian", "Bam Bach Hoi + Trung Wan + Quan Nguyen"],
        ["On toan bo 14 kinh chinh + Mach Doc + Mach Nham", "Kiem tra lai tat ca ten huyet da hoc", "Ve lai ban do co the tat ca kinh"],
        ["Linh Khu Chuong 12: Kinh Biet — 12 duong kinh phu", "Ghi chu y nghia Kinh Biet trong lam sang", "Bat mach + lien he Kinh Biet"],
        ["On tuan 4 — Can/Doc/Nham + tong ket 14 kinh", "Tu test 30 cau hoi vi tri huyet", "Bat mach tong hop"],
        # Week 5 — Cham Cuu Dai Thanh Q2: Thu phap
        ["Doc Cham Cuu Dai Thanh Q2: Thu phap co ban — Tiet khau, Tich khau", "Ve goc cam kim dung cho tung vi tri", "Tap tren bo-tui/cam cam"],
        ["Doc Cham Cuu Dai Thanh Q2: Dac Khi — cam giac khi da khi", "Ghi chu mo ta Dac Khi: tuc, nong, lan, dien", "Bam diem + tu mo ta cam giac"],
        ["Doc Cham Cuu Dai Thanh Q2: Bo phap va Ta phap", "Ghi chu quy tac Bo — Ta theo Nan Kinh", "Phan tich: khi nao Bo, khi nao Ta?"],
        ["Doc Cham Cuu Dai Thanh Q2: Cuu phap (ngai cuu)", "Ghi chu cach lam cuu diem va cuu truc tiep", "Hieu ly thuyet, khong thuc hanh cuu"],
        ["Doc Cham Cuu Dai Thanh Q2: Phoi huyet ca ban — Nguyen-Lac, Du-Mo", "Ghi chu quy tac phoi Nguyen-Lac", "Ap dung: Ty huu phoi Tam Am Giao + Cong Ton"],
        ["Doc Cham Cuu Dai Thanh Q2: Ngu Du huyet — Tinh Huynh Du Kinh Hop", "Ghi chu Ngu hanh tuong ung cua Ngu Du", "Ve bang Ngu Du 12 kinh"],
        ["On tuan 5 — thu phap + Dac Khi + Bo Ta", "Tu dat 10 cau hoi ve thu phap", "Thao luan voi ban hoc neu co"],
        # Week 6 — Hoang De Minh Duong Cham Kinh
        ["Doc Hoang De Minh Duong Cham Kinh: Mo dau, lich su", "So sanh voi Cham Cuu Dai Thanh", "Ghi chu diem khac biet co ban"],
        ["Hoang De Minh Duong: Huyet Vi goc cua 14 kinh (khac so voi Cham Cuu Dai Thanh)", "Ghi chu 10 huyet vi tri khac biet", "Bat mach + lien he vi tri huyet co dien"],
        ["Hoang De Minh Duong: Cam Dac Khi co dien — mo ta trong van ban", "So sanh voi mo ta hien dai", "Bam Tuc Tam Ly + tu mo ta cam giac"],
        ["Linh Khu Chuong 2: Ban Thu — Bien chung, ngu nhan cham", "Ghi chu 5 nguyen tac cam cham", "Phan tich: khi nao khong cham?"],
        ["Linh Khu Chuong 3: Tieu Cham — 9 loai kim co dien", "Ve 9 loai kim + cong dung", "Hieu lich su, lien he kim hien dai"],
        ["Linh Khu Chuong 4: Buu Khi — Khi cua huyet va kim", "Ghi chu ly thuyet Khi tuong tac voi kim", "Thien + cam nhan Khi tai Bach Hoi"],
        ["On tuan 6 — Hoang De Minh Duong + Linh Khu", "Ghi chu 5 phat hien quan trong nhat tuan nay", "Bat mach tong hop"],
        # Week 7 — Phoi huyet lam sang
        ["Phoi huyet cho benh dau dau: Bach Hoi, Thai Duong, Phong Tri, Hop Coc", "Hieu co che moi huyet", "Bam tu phat Phong Tri + Hop Coc"],
        ["Phoi huyet cho benh mat ngu: Tam Mo, An Mien, Shen Men, Tam Am Giao", "Ghi chu co che 4 huyet nay", "Bam An Mien + Shen Men buoi toi"],
        ["Phoi huyet cho tinh than: Bach Hoi, Noi Quan, Thai Xung, Tam Mo", "Hieu 'Hai vai giang than' trong cham cuu", "Thien + cam nhan 4 huyet"],
        ["Phoi huyet cho ho hap: Phe Du, Trung Phu, Phong Mon, Dinh Chuan", "Phan tich 4 tang o Bo phap Phe", "Hoc hoi tho sau co dich"],
        ["Phoi huyet cho tieu hoa: Tuc Tam Ly, Trung Wan, Ty Du, Vi Du", "Ghi chu co che Ty Vi khi hoa", "Bam Tuc Tam Ly buoi sang"],
        ["Phoi huyet cho dau lung: Than Du, Wei Zhong (Ui Trung), Kun Lun (Khon Luan)", "Hoc tam hoang bao (back shu + command point)", "Bam nhe Than Du + Wei Zhong"],
        ["On tuan 7 — phoi huyet lam sang 6 chu de", "Viet 3 ca lam sang ngan tu phoi huyet vua hoc", "Bat mach + nhan dinh kien nghi"],
        # Week 8 — Kinh Can va Kinh Biet
        ["Linh Khu Chuong 13: Kinh Can — he thong co mac", "Ghi chu 12 Kinh Can + anh huong", "Lien he Kinh Can voi fascia hien dai"],
        ["Phan tich Kinh Can Duong Minh: lien he mat truoc toan than", "Ve so do Kinh Can Don Minh", "Cam nhan co tru truoc co the"],
        ["Phan tich Kinh Can Thai Duong: lien he mat sau toan than", "Ve so do Kinh Can Thai Duong", "Cam nhan co tru sau co the"],
        ["Phan tich Kinh Can Thieu Duong: lien he mat ben toan than", "Ve so do Kinh Can Thieu Duong", "Cam nhan co tru ben co the"],
        ["Ung dung Kinh Can trong dieu tri dau co xuong khop", "Ghi chu 5 tinh huong dieu tri", "Phan tich: phuong cham Kinh Can vs Kinh Chinh"],
        ["Linh Khu Chuong 11: Kinh Biet — moi noi 6 hop", "Ve so do 6 Hop cua Kinh Biet", "Hieu y nghia Kinh Biet trong benh noi tang"],
        ["On tuan 8 — Kinh Can + Kinh Biet", "Ghi chu 10 diem quan trong nhat", "Bat mach + lien he kinh la"],
        # Week 9
        ["Loa Cham (nhi cham): so do tai + diem tuong ung", "Hoc 10 diem tai quan trong nhat", "Bam diem tai tac giai dau dau"],
        ["Vuong Chau Cham (cham tren mat): so do mat", "Hoc 5 diem mat co ban", "Ghi chu lich su vuong chau cham"],
        ["Duoi Cham (cham chan sau): 14 diem co ban", "Hoc vi tri 14 diem Duoi Cham", "Bam nhe long ban chan + cam nhan"],
        ["Nhan trung + Bach Hoi + Noi Quan — bo 3 huyet an than", "Ghi chu chi dinh dac biet", "Bam tu nhan trung khi met moi"],
        ["Hoc cham cuu theo thoi gian — Linh Quy Bat Phap", "Ghi chu nguyen tac chon gio cham", "Xac dinh gio va huyet cho ngay hom nay"],
        ["Hoc cham cuu theo thoi gian — Ngo Xa Luu Chu", "So sanh Linh Quy vs Ngo Xa", "Ghi chu uu nhuoc diem moi phuong phap"],
        ["On tuan 9 — nhi cham + bo sung phap", "Ghi chu 5 phuong phap cham cuu bo sung da hoc", "Bat mach + nhan dinh"],
        # Week 10
        ["Thieu Am Cham Phap — 8 phap cua Tam va Than", "Ghi chu chi dinh 8 phap", "Phan tich: khi nao dung Thieu Am Cham?"],
        ["Binh Diem Cham Phap — cham diem hoa xuong", "Hoc 20 diem hoa xuong co ban", "Bat mach + lien he co xuong"],
        ["Tong hop phoi huyet nang cao: Mu-Du-Lac-Nguyen", "Ghi chu quy tac phoi 4 loai huyet nang cao", "Ap dung: phac do benh Ty huu"],
        ["Ung dung Ngu Du huyet theo Ngo Hanh bi thang (mother-son)", "Tinh huyet cho Phe huu = bo Ty (Thai Bai) + ta Tam (Thieu Phu)", "Thuc hanh tinh huyet mot benh"],
        ["Phan tich bien chung cham cuu: 8 tinh huong cam cham", "Ghi chu xu ly tai bien", "Hieu ly thuyet an toan"],
        ["On tuan 10 — phap cham nang cao", "Tu test 20 cau hoi phoi huyet", "Bat mach tong hop"],
        ["Nghi — thien + cam nhan Khi sau 10 tuan hoc cham", "Viet nhat ky: su thay doi tu nhan thuc ve co the", "Cam nhan toan than"],
        # Week 11-15: Chuyen sau lam sang
        ["Cham cuu benh ho hap: Viem mui di ung — phac do 5 huyet", "Ghi chu co che moi huyet", "Bat mach + nhan dinh Phe Khi"],
        ["Cham cuu benh ho hap: Hen suyen man tinh — phac do 6 huyet", "Phan tich Bo vs Ta trong hen suyen", "Ap dung ly thuyet Phe Ty Than"],
        ["Cham cuu benh tieu hoa: Viem dai trang co nang — phac do", "Hoc quy tac phoi Ty Vi tren/duoi", "Bat mach + ghi nhan dinh Ty Vi"],
        ["Cham cuu benh tieu hoa: Tao bon man tinh — phac do 4 huyet", "Phan biet tao bon Khi huu vs Am huu", "Ap dung bien chung chon phac do"],
        ["Cham cuu benh xuong khop: Dau vai — kinh Tieu Truong + Dom", "Hoc diem ashi + kinh duong", "Bat mach + phan tich kinh bi thuong"],
        ["Cham cuu benh xuong khop: Dau that lung — kinh Than/Bang Quang", "Hoc phac do dau lung cap/man", "Bam Wei Zhong + Than Du nhe"],
        ["On tuan 11 — ho hap + tieu hoa + xuong khop", "Viet 3 ca lam sang day du", "Bat mach 3 ca"],
        ["Cham cuu benh than kinh: Dau dau Migraine — phac do", "Hoc Thieu Duong + Duong Minh cho migraine", "Bam Phong Tri + Noi Quan"],
        ["Cham cuu benh than kinh: Mat ngu — phac do 5 huyet + cuu", "Ghi chu ket hop cham + cuu cho mat ngu", "Bam An Mien buoi toi"],
        ["Cham cuu tram cam nhe: Bach Hoi, Noi Quan, Thai Xung, Tam Mo, Trung Wan", "Hoc 'Hai co giang than' cho tram cam", "Thien + bam 5 huyet tren"],
        ["Cham cuu benh phu khoa: Roi loan kinh nguyet — phac do Can Ty Than", "Ghi chu bien chung Can huu, Tam Huyet huu", "Bat mach tay trai phu nu"],
        ["Cham cuu pho tro sut can: Nhi cham + kinh Ty Vi", "Hoc phac do nhi cham 5 diem", "Bam diem tai cho Ty Vi"],
        ["Cham cuu ha huyet ap: Phe Du, Tam Du, Noi Quan, Tuc Tam Ly", "Ghi chu co che on dinh huyet ap qua Khi hoa", "Bat mach + do huyet ap neu co the"],
        ["On tuan 12-13 — benh than kinh + phu khoa + noi tiet", "Viet 5 ca lam sang day du 5 chu de", "Bat mach 5 nguoi"],
        # Week 14-15: Tong hop va chuan bi thi
        ["Tong on Cham Cuu Dai Thanh Q1: 14 kinh chinh + 361 huyet quan trong", "Lam flashcard 50 huyet co ban nhat", "Bat mach + nhan dinh kinh nao hoat dong nhat"],
        ["Tong on Cham Cuu Dai Thanh Q2: Thu phap + Bo Ta + Ngu Du", "Tu test 20 cau hoi thu phap", "Thuc hanh bo ta phap tren ban than"],
        ["Tong on Hoang De Minh Duong + Linh Khu Kinh Mach", "Ve lai 14 kinh co ban tu tri nho", "Bat mach tong hop"],
        ["Tong on phoi huyet lam sang: 10 benh pho bien", "Viet 10 phac do ngan gon", "Bat mach + chuan doan thu"],
        ["Tong on cham dac biet: nhi cham, duoi cham, bo sung phap", "Tom tat 1 trang", "Thien + cam nhan Khi"],
        ["Lam de thi thu 80 cau cham cuu", "Ghi chu cac cau sai", "Bat mach"],
        ["On lai cac cau sai — phan tich nguyen nhan", "Hieu sau tung cau sai", "Bat mach + nghi som"],
        # Week 16-17: On thi
        ["On thi: Vi tri huyet 14 kinh (40 cau)", "Lam chac", "Bat mach"],
        ["On thi: Thu phap + Bo Ta + Ngu Du (40 cau)", "Lam chac", "Bat mach"],
        ["On thi: Phoi huyet lam sang (40 cau)", "Lam chac", "Bat mach"],
        ["On thi: Cham dac biet + Kinh Biet + Kinh Can (40 cau)", "Lam chac", "Bat mach"],
        ["On thi lan 2: Vi tri huyet 14 kinh", "Ghi chu diem yeu con lai", "Bat mach"],
        ["On thi lan 2: Thu phap + lam sang", "Ghi chu diem yeu con lai", "Bat mach"],
        ["Nghi — thien + on nhe", "Cam on ban than vi 140 ngay kien tri", "Bat mach + nghi som"],
        # Week 18
        ["On tong luc — tat ca diem yeu", "Lam 40 cau ngau nhien lan cuoi", "Bat mach"],
        ["Kiem tra ky nang thuc hanh: xac dinh vi tri 20 huyet quan trong", "Tu danh gia do chinh xac", "Bam diem + cam nhan Dac Khi"],
        ["On phoi huyet: 10 benh pho bien — phac do nhanh", "Viet lai phac do khong nhin tai lieu", "Bat mach + nhan dinh"],
        ["On thu phap + an toan cham cuu", "Kiem tra lai quy tac cam cham", "Hieu sau an toan truoc thuc hanh"],
        ["Tong on cuoi — moi phan 30 phut", "Ghi chu tu tin vao tung phan", "Bat mach tong hop"],
        ["Nghi ngoi + chuan bi tam ly", "Ngu du giac, khong on khuya", "Bat mach buoi sang binh thuong"],
        ["Ngay thi Phase 2 — bot se gui de thi hom nay", "Giu tam binh tinh, tin vao 140 ngay hoc", "Bat mach truoc khi thi"],
    ] + [  # padding to exactly 140 entries (20 weeks × 7 = 140)
        [f"On tap Cham Cuu ngay {i+1}", "Ghi chu 3 diem can on", "Bat mach + lien he ly thuyet"]
        for i in range(140 - 20*7)  # fills any gap if above is short
    ],

    3: [  # Phase 3 — 32 weeks = 224 days — Thuong Han & Tap Benh
        # Week 1 — Thuong Han Luan: Thai Duong kinh
        ["Doc Thuong Han Luan: Mo dau, Luc kinh he thong", "Ghi chu 6 kinh bien chung co ban", "Bat mach + nhan dinh khi nao dung luc kinh"],
        ["Doc Thuong Han Luan: Thai Duong kinh — Dieu 1-10", "Ghi chu chung trung phong vs chung thang han", "Bat mach: tim Phu Khuan, Phu Hoan"],
        ["Doc Thuong Han Luan: Thai Duong kinh — Dieu 11-30: Que Chi thang bien bien", "Hoc 3 phuong tieu Que Chi", "Ghi chu: khi nao them/bot thuoc trong Que Chi thang"],
        ["Doc Thuong Han Luan: Thai Duong kinh — Dieu 31-60: Ma Hoang thang + bien bien", "Phan biet Ma Hoang vs Que Chi chi dinh", "Bat mach: Phu Khuan (phong) vs Phu Khun (han)"],
        ["Doc Thuong Han Luan: Thai Duong kinh — Dieu 61-100: Bien bien phuc tap", "Ghi chu 10 phuong quan trong nhat", "Ap dung bien bien: nguoi sot khong ra mo hoi"],
        ["Doc Thuong Han Luan: Thai Duong kinh — Dieu 101-130: Nhap ly bien bien", "Ghi chu dieu kien chuyen kinh", "Bat mach: Phu Dai — am nhiet tu Thai Duong"],
        ["On tuan 1 — Thai Duong kinh Dieu 1-130", "Viet tom tat co che Thai Duong benh", "Bat mach tong hop"],
        # Week 2
        ["Doc Thuong Han Luan: Thai Duong kinh — Dieu 131-180: Bien chung nang hon", "Ghi chu benh ham hung, ket hung", "Bat mach: Tram Khun — am sung benh ly"],
        ["Doc Thuong Han Luan: Thai Duong kinh — Dieu 181-220", "Hoan thanh Thai Duong phan", "Tom tat Thai Duong: 3 de tiep can"],
        ["Hoc Que Chi thang — phan tich 6 vi thuoc", "Ghi chu co che hoat dong cua tung vi", "Bat mach Phu Hoan — chi dinh Que Chi"],
        ["Hoc Ma Hoang thang — phan tich 4 vi thuoc", "So sanh Ma Hoang vs Que Chi co che", "Bat mach Phu Khun — chi dinh Ma Hoang"],
        ["Hoc Ma Hoang Que Chi Cac Ban Thang — giai giai trung gian", "Ghi chu bien bien phong vs han con lai", "Bat mach + phan tich Phu Nhuoc vs Phu Khun"],
        ["Hoc Sai Ho thang — Thieu Duong chi phuong", "Ghi chu 7 chung trung thuong cua Sai Ho thang", "Bat mach Huyen — chi dinh Sai Ho"],
        ["On tuan 2 — Ma Hoang, Que Chi, Sai Ho, + bien bien co ban", "Tu test 10 cau bien bien", "Bat mach tong hop"],
        # Week 3 — Duong Minh kinh
        ["Doc Thuong Han Luan: Duong Minh kinh — Dieu 179-210", "Ghi chu Kinh chung vs Phu chung", "Bat mach: Thuc Dai, Tram Thuc — Duong Minh"],
        ["Doc Thuong Han Luan: Duong Minh kinh — Dieu 211-250", "Hoc Ngo Linh Tan — thanh nhiet cho phep", "Bat mach Hoan Dai — vong tham"],
        ["Hoc Bai Ho thang — Thach Cao thanh nhiet phe nhiet", "Phan tich Bai Ho vs Thach Cao chi dinh", "Bat mach Hoan Dai + Sac Dai"],
        ["Hoc Dieu Viet Thang (Bai Ho Tuong Nham Thang) — duong am nhiet", "Phan biet Nhiet vs Am huu Duong Minh", "Bat mach + cham doan Duong Minh"],
        ["Hoc 3 Thanh Khi thang: Dai/Tieu/Dieu Viet", "Ghi chu chi dinh tung phuong qua trieu chung phu tuc", "Bat mach: Tram Thuc Dai + trieu chung"],
        ["On tuan 3 — Duong Minh kinh", "Viet so do bien chung Duong Minh", "Bat mach tong hop"],
        ["Hoc Hop Dong thang — Tuc Thieu Duong kinh he", "Phan tich 6 phuong Tuc Thieu Duong", "Bat mach Huyen Te — Thieu Duong huu"],
        # Week 4 — Thieu Duong + Thai Am kinh
        ["Doc Thuong Han Luan: Thieu Duong kinh — Dieu 263-272", "Ghi chu tam chung + tu cam", "Bat mach Huyen Khun — Thieu Duong chinh mac"],
        ["Hoc Sai Ho Que Chi Can Khuong thang — Thieu Duong vao Tang", "Phan tich co che Sai Ho bien phuong", "Bat mach + nhan dinh Tang bi anh huong"],
        ["Doc Thuong Han Luan: Thai Am kinh — Dieu 273-280", "Ghi chu Thai Am thuong han trieu chung", "Bat mach Hoan Te — Thai Am"],
        ["Hoc Ly Trung thang — Bo trung ich Ty khi", "Phan tich Ly Trung 4 vi + co che", "Bat mach + phan tich huu Ty Khi"],
        ["Hoc Thu Bui thang — gio han o trong kinh", "Ghi chu dieu kien chi dinh chu bui", "Bat mach Tram Hoan + lanh bung"],
        ["Hoc Tu Nghich thang — hoi duong cuu nghich", "Phan tich 3 bien bien Tu Nghich thang", "Bat mach Tu Tram — Duong huu"],
        ["On tuan 4 — Thieu Duong + Thai Am + phuong tieu", "Viet so do 3 kinh vua hoc", "Bat mach tong hop"],
        # Week 5 — Thieu Am + Quyet Am kinh
        ["Doc Thuong Han Luan: Thieu Am kinh — Dieu 281-325", "Ghi chu Thieu Am: Han hoa va Nhiet hoa", "Bat mach Te + Te Sac"],
        ["Hoc Ma Hoang Phu Tu Thieu Am Thang — am han Thieu Am", "Phan tich Ma Hoang Phu Tu co che", "Bat mach Te Tram — Thieu Am han"],
        ["Hoc Hoang Lien A Giao thang — am nhiet Thieu Am", "So sanh Han hoa vs Nhiet hoa Thieu Am", "Bat mach Te Sac — Thieu Am nhiet"],
        ["Doc Thuong Han Luan: Quyet Am kinh — Dieu 326-381", "Ghi chu Quyet Am nong lanh lan lon", "Bat mach Quyet + Huan"],
        ["Hoc Vu Mai thang — Qyet Am phuc tap", "Phan tich Vu Mai thang 10 vi", "Bat mach + nhan dinh Can Tam Nhu Toan"],
        ["Hoc Duong Phuc thang — khi khue duong nghich", "Ghi chu co che duong khi xu huong", "Bat mach Tram — duong am huu"],
        ["On tuan 5 — Thieu Am + Quyet Am", "Ve so do 6 kinh bien chung day du", "Bat mach tong hop"],
        # Week 6 — Tap benh Luan
        ["Doc Tu Thanh Tam Nguyen: Duong Khi & Menh Mon — Quyen 1", "Ghi chu Hoang Nguyen Ngu ly thuyet Duong Khi", "Bat mach + lien he Menh Mon"],
        ["Doc Tu Thanh Tam Nguyen: Phe Khi & Trung Tieu — Quyen 2", "Phan tich Trung Khi khai thong Phe Khi", "Bat mach Thon tay phai + nhan dinh Phe"],
        ["Doc Tu Thanh Tam Nguyen: Ty Vi ly luan — Quyen 3", "Ghi chu quan diem Hoang Nguyen Ngu ve Trung Tieu", "Bat mach Quan tay phai + nhan dinh Vi"],
        ["Doc Tu Thanh Tam Nguyen: Than Khi & Menh Mon — Quyen 4", "Phan tich Than Am vs Than Duong — quan diem Hoang Nguyen Ngu", "Bat mach Xich 2 tay"],
        ["Doc Tap Benh Luan — Truong Trong Canh: Tong quan Kim Quuy Yeu Luoc", "Ghi chu 6 phan trong cua Kim Quuy", "Bat mach"],
        ["Doc Kim Quuy Yeu Luoc: Bien chung Hu Lao — Huu Gui Thang", "Hoc Huu Gui Thang co che bo Than Duong", "Bat mach Xich Nhuoc + nhan dinh Than Duong huu"],
        ["On tuan 6 — Tu Thanh Tam Nguyen + Kim Quuy", "Ghi chu 5 diem quan trong nhat", "Bat mach tong hop"],
        # Week 7-10: Kim Quuy Yeu Luoc — bien chung tap benh
        ["Doc Kim Quuy: Bien chung am bo truong chi benh — Viet Bi thang", "Hoc Viet Bi thang + bien bien", "Bat mach Phu Tram Khun"],
        ["Doc Kim Quuy: Bien chung Hung Bi — Qua Lou Xie Bai thang", "Hoc Hung Bi am han vs nhiet ung", "Bat mach Tram Khun — Hung Bi"],
        ["Doc Kim Quuy: Bien chung Khi Nen — Kim Quy Shen Khi Wan", "Hoc Than Khi Hoan co che", "Bat mach Xich Nhuoc — Than am"],
        ["Doc Kim Quuy: Bien chung phu tu Menh Mon — Wen Jing thang", "Hoc Van Kinh thang bi mat cho phu tu Menh Mon huu", "Bat mach + phan tich Can Huyet huu phu nu"],
        ["Doc Kim Quuy: Bien chung thuy ung — 5 loai thuy ung", "Phan biet Phong/Phu/Chinh/Thach/Hoang Hoa thuy", "Bat mach + nhan dinh thuy huu"],
        ["Doc Kim Quuy: Bien chung hung ung ho ho — bien bien phuc tap", "Ghi chu 10 phuong tieu pho bien nhat Kim Quuy", "Bat mach + nhan dinh Phe/Vi khi Tan Dich"],
        ["On tuan 7-8 — Kim Quuy Yeu Luoc bien chung", "Viet 5 ca lam sang voi Kim Quuy phuong tieu", "Bat mach 5 nguoi khac nhau"],
        ["Doc Kim Quuy: Bien chung khuong chuot lai benh — 4 loai", "Hoc 4 loai khuong chuot lai + phuong tieu", "Bat mach + nhan dinh am huong lai"],
        ["Doc Kim Quuy: Bien chung huyet chung — Giao Ai thang", "Hoc Giao Ai thang + bien bien Can Huyet huu", "Bat mach + nhan dinh Can Tang"],
        ["Doc Kim Quuy: Ngu tang phong", "Hoc 5 dang phong bieu hien theo tang", "Bat mach + nhan dinh tang bi anh huong"],
        ["Doc Kim Quuy: Ly huu (lien la lau ngay) — bien bien", "Phan biet han/nhiet/hu/thuc ly", "Bat mach + nhan dinh vi cuong yeu"],
        ["Doc Kim Quuy: O du, to, tri — bien bien ngo tang benh chu", "Ghi chu ngo tang benh chu bien bien", "Bat mach + phan tich 5 tang"],
        ["Doc Kim Quuy: Vong cu, bao bi thang", "Hoc cac phuong tieu Kim Quuy pho bien nhat", "Bat mach tong hop"],
        ["On tuan 9-10 — Kim Quuy toan tap", "Viet 10 ca lam sang ngan gon", "Bat mach tong hop + nhan dinh lam sang"],
        # Week 11-16: Thuc hanh bien chung
        ["Thuc hanh bien chung: Benh sot viem hong — Thai Duong hay Duong Minh?", "Phan tich qua mach + trieu chung", "Bat mach + chuan doan thu"],
        ["Thuc hanh bien chung: Ho co dom vang — Tang nao?", "Bien bien Can Phe vs Vi nhiet", "Bat mach + phac do thu"],
        ["Thuc hanh bien chung: Met moi nguoi nha lam nhieu — Hu lao gi?", "Bien chung Ty Khi huu vs Than Am huu", "Bat mach + phac do"],
        ["Thuc hanh bien chung: Dau bung lanh, muon uong nuoc nong — Han hay Nhiet?", "Ap dung Ly Trung bien chung", "Bat mach Hoan Te hoac Te Tram"],
        ["Thuc hanh bien chung: Moi kho khong muon uong — Tang nao?", "Bien chung Am huu vs Nhiet huu", "Bat mach + ghi nhat ky"],
        ["Thuc hanh bien chung: Them an nguot — Ty huu hay Vi nhiet?", "Phan tich Trung Tieu 3 tang", "Bat mach Quan 2 tay + nhan dinh"],
        ["On tuan 11-12 — bien chung thuc hanh", "Viet 6 ca lam sang hoan chinh", "Bat mach 6 nguoi"],
        ["Thuc hanh bien chung: Dau dau sang khi thuc day — Am hay Duong?", "Phan tich Duong Khi va Noi Khi", "Bat mach buoi sang som"],
        ["Thuc hanh bien chung: Hoi hop, lo lang — Tang nao?", "Bien chung Tam Huyet vs Tam Khi huu", "Bat mach Thon tay trai"],
        ["Thuc hanh bien chung: Da kho bong tuoc — Phong hay Huyet kho?", "Bien chung Can Huyet + Phong noi sinh", "Bat mach + nhan dinh Can khi"],
        ["Thuc hanh bien chung: Mat ngu nhieu mo — Tam Tang hay Can Tang?", "Phan tich Tam Than + Can Hoa", "Bat mach + phac do"],
        ["Thuc hanh bien chung: Tre em hay quoc khoc — Tang nao?", "Bien chung tre em theo Thieu Am Quyet Am", "Bat mach tre em (neu co the)"],
        ["On tuan 13-14 — bien chung phuc tap", "Viet 6 ca lam sang moi", "Bat mach + tong ket"],
        # Week 15-20: Ky nang tong hop
        ["Bien bien Thieu Duong phuc hap: Sai Ho + bien bien vao Tang", "Hoc 6 phuong Sai Ho bien bien", "Bat mach Huyen Khun"],
        ["Bien bien ha phap: Phu, Hoan, Viet — khi nao dung?", "Ghi chu 5 bien bien sau khi ha phap", "Bat mach + nhan dinh"],
        ["Bien bien Duong Minh va Thieu Am phuc hap: 3 am kep 2 duong", "Phan tich 6 phac do dac biet", "Bat mach + chuan doan"],
        ["Hoc phap do cho tremantle (phuong tieu co dieu chinh)", "Tong hop 10 phuong tieu hay bien doi nhat", "Bat mach + viet phac do thu"],
        ["On tuong tac thuoc: 18 phan, 19 ky, 6 co than", "Ghi chu cac cap thuoc khong ket hop", "Hieu an toan truoc khi ke don"],
        ["Ket hop Cham Cuu + Thuong Han: khi nao them cham?", "Ghi chu 5 tinh huong phat huy nhat", "Bat mach + phac do ket hop"],
        ["On tuan 15-16 — nang cao", "Tu test 30 cau hoi bien chung", "Bat mach tong hop"],
        # Week 17-20: Chuan bi thi
        ["On thi: Thuong Han 6 kinh bien chung (40 cau)", "Lam chac", "Bat mach"],
        ["On thi: Phuong tieu Thuong Han 20 phuong quan trong (40 cau)", "Lam chac", "Bat mach"],
        ["On thi: Kim Quuy bien chung tap benh (40 cau)", "Lam chac", "Bat mach"],
        ["On thi: Tu Thanh Tam Nguyen + Duong Khi ly thuyet (40 cau)", "Lam chac", "Bat mach"],
        ["On lan 2: 6 kinh + phuong tieu", "Ghi chu diem yeu con lai", "Bat mach"],
        ["On lan 2: Kim Quuy + Ly luan nang cao", "Ghi chu diem yeu con lai", "Bat mach"],
        ["Nghi — thien + on nhe", "Viet nhat ky tu danh gia 224 ngay hoc", "Bat mach + nghi som"],
        ["On tong luc — tat ca diem yeu", "Lam 40 cau ngau nhien lan cuoi", "Bat mach"],
        ["Kiem tra bien chung thuc hanh: phan tich 3 ca lam sang", "Tu danh gia chinh xac bien chung", "Bat mach 3 ca"],
        ["Tong on cuoi — moi phan 30 phut", "Ghi chu tu tin vao tung phan", "Bat mach tong hop"],
        ["Nghi ngoi + chuan bi tam ly", "Ngu du giac, khong on khuya", "Bat mach buoi sang"],
        ["Ngay thi Phase 3 — bot se gui de thi hom nay", "Giu tam binh tinh, tin vao 224 ngay hoc", "Bat mach truoc khi thi"],
    ] + [  # padding to 224
        [f"On tap Thuong Han ngay {i+1}", "Ghi chu 3 diem can on", "Bat mach + lien he ly thuyet"]
        for i in range(224 - 32*7)
    ],

    4: [  # Phase 4 — 20 weeks = 140 days — On Benh Hoc
        # Week 1 — On Benh Dieu Bien
        ["Doc On Benh Dieu Bien: Mo dau, lich su On Benh hoc", "Ghi chu su khac biet On Benh vs Thuong Han", "Bat mach + nhan dinh Khi nhiet"],
        ["Doc On Benh Dieu Bien: Ve Khi Dinh Huyet 4 tang co ban", "Ghi chu trieu chung moi tang", "Bat mach + phan loai tang mach dang o"],
        ["Doc On Benh Dieu Bien: Ve phan — Bieu phan nhiet chung", "Hoc Mac Kinh — Ngan Kieu thang cho Ve phan", "Bat mach Phu Sac — Ve phan"],
        ["Doc On Benh Dieu Bien: Khi phan — Nhiet nap Duong Minh", "Hoc Bai Ho thang trong On Benh", "Bat mach Sac Hoan Dai — Khi phan"],
        ["Doc On Benh Dieu Bien: Dinh phan — nhiet nhap Dinh Khi", "Hoc Thanh Dinh thang — thanh nhiet luong dinh", "Bat mach Sac Te — Dinh phan"],
        ["Doc On Benh Dieu Bien: Huyet phan — nhiet doc thien huyet", "Hoc Tay Giao thang — luong huyet giai doc", "Bat mach Te Sac — Huyet phan"],
        ["On tuan 1 — Ve Khi Dinh Huyet co ban", "Ve so do 4 tang Ve Khi Dinh Huyet", "Bat mach tong hop + nhan dinh tang"],
        # Week 2 — On Nhiet Luan (Diep Thien Si)
        ["Doc On Nhiet Luan: Nhiet benh theo kinh mach", "So sanh On Nhiet vs Ve Khi Dinh Huyet cua Ngo Khuyen", "Bat mach + phan tich"],
        ["Doc On Nhiet Luan: Ngu Phong Nhiet khi", "Hoc 5 loai phong nhiet Diep Thien Si", "Bat mach Phu Sac Hoan — phong nhiet"],
        ["Doc On Nhiet Luan: Phuc nhiet, tro nhiet, tan nhiet", "Ghi chu cac phap thanh nhiet On Benh", "Bat mach + nhan dinh nhiet do"],
        ["Doc On Nhiet Luan: Am huu trong On Benh — bao ve Am dich", "Hoc quy tac bao Am trong benh nhiet", "Bat mach + ghi nhat ky"],
        ["Tong hop On Nhiet Luan: 10 nguyen tac tri nhiet benh", "Viet 10 nguyen tac theo thu tu uu tien", "Bat mach + ap dung nguyen tac"],
        ["So sanh On Nhiet Luan (Diep Thien Si) vs On Benh Dieu Bien (Ngo Khuyen)", "Ghi chu 5 diem khac biet chinh", "Bat mach tong hop"],
        ["On tuan 2 — On Nhiet Luan toan bo", "Viet bai phan tich ngan ve phuong phap Diep Thien Si", "Bat mach + cam nhan"],
        # Week 3 — Tam Tieu bien chung
        ["Doc On Benh Dieu Bien: Thuong Tieu — Phe + Tam thanh nhiet", "Hoc Bac Ho Nguyet Son thang cho Phe Khi Nhiet", "Bat mach Thon tay phai — Phe Nhiet"],
        ["Doc On Benh Dieu Bien: Trung Tieu — Ty Vi nhiet Tan Dich", "Hoc Teng Yu thang cho Trung Tieu Nhiet", "Bat mach Quan tay phai — Vi Nhiet"],
        ["Doc On Benh Dieu Bien: Ha Tieu — Than + Can am huu", "Hoc Gia Giam Phuc Mach thang cho Ha Tieu Nhiet", "Bat mach Xich tay trai — Than Am"],
        ["So sanh Ve Khi Dinh Huyet vs Tam Tieu bien chung", "Ghi chu khi nao dung phuong phap nao", "Bat mach + chuan doan theo 2 he"],
        ["Ung dung thuc te: benh nhiet do cao — Khi phan hay Dinh phan?", "Phan tich qua trieu chung + mach", "Bat mach + chuan doan thu"],
        ["Ung dung thuc te: sot 5 ngay khong ha — Diep Thien Si phap", "Ap dung On Nhiet Luan cho truong hop phuc tap", "Bat mach + phac do"],
        ["On tuan 3 — Tam Tieu bien chung + ung dung", "Viet 3 ca lam sang theo 2 he thong", "Bat mach 3 nguoi"],
        # Week 4 — On Benh dac biet va tap chung
        ["Doc On Benh Dieu Bien: On Dich (dich benh)", "Ghi chu dac diem benh dich vs thuong nhiet", "Bat mach + nhan dinh doc khi"],
        ["Doc On Benh Dieu Bien: Shu Wen dich On — Thanh Wen Bai Du thang", "Hoc phuong tieu dieu tri On Dich", "Ghi chu lich su On Dich Trung Quoc"],
        ["Doc On Benh Dieu Bien: Phu tu On (On benh o phu nu co thai)", "Hoc bien bien dac biet phu tu On", "Bat mach phu nu + nhan dinh"],
        ["Doc On Benh Dieu Bien: Nhu Ngo (buon ngu qua muc o On benh)", "Ghi chu co che Tam Khi bi an", "Bat mach + nhan dinh Tam Khi"],
        ["Tong hop: 6 chung tap cua On Benh hoc can biet", "Viet bang tom tat bien chung <-> phuong tieu", "Bat mach + ap dung"],
        ["Doc Wen Re Lun (tiep tuc): Xu ly nhiet nhap Tam Bao", "Hoc Ngu Sam Tan va Qing Gong thang", "Bat mach Te Sac — Huyet phan, Tam Bao"],
        ["On tuan 4 — On Dich + tap chung + Tam Bao nhiet", "Viet 5 ca lam sang On Benh", "Bat mach tong hop"],
        # Week 5-8: Thuc hanh va tong hop
        ["So sanh Thuc hanh: Thuong Han vs On Benh — khi nao dung cai nao?", "Ghi chu 10 tieu chi phan biet", "Bat mach + chuyen huong bien chung"],
        ["Ket hop Thuong Han + On Benh trong 1 ca lam sang phuc tap", "Viet ca lam sang phuc tap 2 he thong", "Bat mach + phac do ket hop"],
        ["Phan tich: benh sot xuat huyet theo On Benh hoc", "Ap dung Ve Khi Dinh Huyet phan tich tu ca", "Bat mach + nhan dinh giai doan"],
        ["Phan tich: viem phoi COVID-19 theo On Benh hoc", "Ap dung Tam Tieu bien chung cho benh phoi", "Ghi chu: On Benh hoc va benh hien dai"],
        ["Phan tich: sot rot (malaria) qua On Benh hoc", "Hoc Triet Ngu thang cho sot lai hai ngay", "Bat mach Huyen — Can Khi ung phuc"],
        ["Phan tich: liem tiep tuc (Typhoid) qua On Benh hoc", "Ap dung Dinh Khi nhiet cho benh tieu hoa nang", "Bat mach Sac Te — giai doan nang"],
        ["On tuan 5-6 — so sanh Thuong Han + On Benh", "Viet 3 ca lam sang theo he thong chon phuong phap", "Bat mach tong hop"],
        # Week 7
        ["Hoc Mo Nguyen (bao gom On Benh qua khuong chuot lai)", "Ghi chu on benh mua dong qua xuan", "Bat mach Huyen Phu — mo nguyen"],
        ["Hoc Thap On (On Benh ket hop voi Thap tac nhan)", "Phan biet On Benh thuan tuy vs co Thap", "Bat mach Hoan Te — Thap On"],
        ["Hoc Tri On (khi am chet benh lat cat)", "Ghi chu dac diem benh Tri On", "Bat mach Sac Khun"],
        ["Hoc Shu Wen 2: bien bien On Dich khang thuoc", "Phan tich: tai sao On Dich kho tri?", "Ghi chu lich su On Dich va kien giai"],
        ["Tong hop 6 loai On Benh dac biet", "Ve bang phan loai On Benh day du", "Bat mach + phan biet tung loai"],
        ["Phuong tieu On Benh: 15 phuong co ban nhat", "Lam bang flashcard 15 phuong", "Bat mach + chi dinh thu"],
        ["On tuan 7 — On Benh dac biet", "Tu test 10 cau hoi On Benh dac biet", "Bat mach tong hop"],
        # Week 8-10: Tong hop chuyen sau
        ["On Benh hoc hien dai: ung dung trong benh truyen nhiem", "Ghi chu 5 benh truyen nhiem co the dung On Benh", "Bat mach"],
        ["Ket hop On Benh va Phe Khi: ARDS qua goc nhin Dong y", "Phan tich Phe Khi cu tuyet trong On Benh", "Bat mach + nhan dinh Phe"],
        ["Ket hop On Benh va septic shock: Am huu + Duong thoat", "Phan tich hon me sep qua On Benh", "Bat mach Te Sac Vo Luc — Am Duong thoat"],
        ["Phan tich: Phap tri trong On Benh — Phat Han, Ha, Thanh, Tu", "Ghi chu khi nao dung phap gi", "Bat mach + quyet dinh phap tri"],
        ["Ung dung bai thuoc On Benh trong bai thuoc hien dai", "Ghi chu 5 bai thuoc On Benh da duoc nghien cuu hien dai", "Bat mach + ghi nhat ky"],
        ["Ket hop Cham Cuu voi On Benh: tang cuong am khi nhiet benh", "Ghi chu 5 huyet quan trong trong On Benh", "Bam nhe Noi Quan + Tam Am Giao"],
        ["On tuan 8-10 — On Benh hien dai + ket hop", "Viet 5 ca lam sang phuc tap ket hop", "Bat mach 5 nguoi"],
        # Week 11-14: Chuan bi thi
        ["On thi: Ve Khi Dinh Huyet 4 tang (40 cau)", "Lam chac", "Bat mach"],
        ["On thi: On Nhiet Luan — Diep Thien Si (40 cau)", "Lam chac", "Bat mach"],
        ["On thi: Tam Tieu bien chung On Benh (40 cau)", "Lam chac", "Bat mach"],
        ["On thi: On Benh dac biet + ung dung lam sang (40 cau)", "Lam chac", "Bat mach"],
        ["On lan 2: Ve Khi Dinh Huyet + On Nhiet Luan", "Ghi chu diem yeu con lai", "Bat mach"],
        ["On lan 2: Tam Tieu bien chung + On Benh dac biet", "Ghi chu diem yeu con lai", "Bat mach"],
        ["Nghi — thien + on nhe", "Viet nhat ky hanh trinh 560+ ngay hoc Dong y", "Bat mach + nghi som"],
        # Week 15
        ["On tong luc — tat ca diem yeu On Benh", "Lam 40 cau ngau nhien lan cuoi", "Bat mach"],
        ["Kiem tra tong hop: bien chung 3 ca lam sang On Benh", "Tu danh gia chinh xac", "Bat mach 3 ca"],
        ["Tong on cuoi: Ve Khi Dinh Huyet + Tam Tieu + 15 phuong co ban", "Doc nhanh, danh dau diem cot yeu", "Bat mach tong hop"],
        ["Nghi ngoi + chuan bi tam ly", "Ngu du giac, khong on khuya", "Bat mach buoi sang"],
        ["Ngay thi Phase 4 — bot se gui de thi hom nay", "Giu tam binh tinh, tin vao 140 ngay On Benh", "Bat mach truoc khi thi"],
    ] + [  # padding to 140
        [f"On tap On Benh ngay {i+1}", "Ghi chu 3 diem can on", "Bat mach + lien he ly thuyet"]
        for i in range(140 - 20*7)
    ],
}

# Trim or validate counts
for _ph in [2, 3, 4]:
    target = {2: 140, 3: 224, 4: 140}[_ph]
    if len(CURRICULUM[_ph]) > target:
        CURRICULUM[_ph] = CURRICULUM[_ph][:target]
    while len(CURRICULUM[_ph]) < target:
        n = len(CURRICULUM[_ph]) + 1
        CURRICULUM[_ph].append([f"On tap Phase {_ph} ngay {n}", "Ghi chu 3 diem can on", "Bat mach + lien he ly thuyet"])
