# -*- coding: utf-8 -*-
Q0 = [
    # =============================================
    # ÂM DƯƠNG LÝ LUẬN CƠ BẢN — 25 câu (1-25)
    # =============================================
    {"q": "Theo Âm Dương học thuyết, Âm có đặc tính là gì?", "opts": {"A": "Động, nhiệt, sáng", "B": "Tĩnh, lạnh, tối", "C": "Thăng, phát triển, hướng ngoại", "D": "Khởi động, hưng phấn"}, "ans": "B"},
    {"q": "Dương có đặc tính nào sau đây?", "opts": {"A": "Tĩnh lặng, làm mát, hướng nội", "B": "Nhu nhuận, đi xuống", "C": "Động, nhiệt, sáng, hướng ngoại", "D": "Lưu trữ, ức chế"}, "ans": "C"},
    {"q": "Quan hệ nào thể hiện sự 'Âm trong Dương, Dương trong Âm'?", "opts": {"A": "Ban ngày thuộc Dương, ban đêm thuộc Âm", "B": "Ban ngày thuộc Dương nhưng có buổi sáng (Âm trong Dương) và buổi chiều (Dương trong Dương)", "C": "Mùa hè thuộc Âm, mùa đông thuộc Dương", "D": "Phía trên thuộc Âm, phía dưới thuộc Dương"}, "ans": "B"},
    {"q": "Nguyên lý 'Âm Dương đối lập' được thể hiện qua ví dụ nào?", "opts": {"A": "Nước và lửa đối lập nhau", "B": "Ngắn ngắn và dài dài đối lập nhau", "C": "Trời và đất đối lập nhau", "D": "Tất cả các ví dụ trên"}, "ans": "D"},
    {"q": "Trong cơ thể người, Khí thuộc về loại nào?", "opts": {"A": "Âm", "B": "Dương", "C": "Vừa Âm vừa Dương", "D": "Không xếp loại Âm Dương"}, "ans": "B"},
    {"q": "Trong cơ thể người, Huyết thuộc về loại nào?", "opts": {"A": "Dương", "B": "Âm", "C": "Trung tính", "D": "Phụ thuộc vào từng người"}, "ans": "B"},
    {"q": "Tạng phủ trong cơ thể: Tạng thuộc về loại nào?", "opts": {"A": "Dương", "B": "Âm", "C": "Vừa Âm vừa Dương", "D": "Không xếp loại"}, "ans": "B"},
    {"q": "Tạng phủ trong cơ thể: Phủ thuộc về loại nào?", "opts": {"A": "Âm", "B": "Dương", "C": "Trung hòa", "D": "Phụ thuộc chức năng"}, "ans": "B"},
    {"q": "Nguyên lý 'Âm Dương cân bằng động' (quan hệ hòa hợp) có nghĩa là gì?", "opts": {"A": "Âm và Dương luôn bằng nhau tuyệt đối", "B": "Âm và Dương trong trạng thái cân bằng tương đối, luôn điều chỉnh cho nhau", "C": "Âm và Dương không bao giờ thay đổi", "D": "Chỉ có Dương mới quan trọng, Âm chỉ phụ trợ"}, "ans": "B"},
    {"q": "Hiện tượng 'Âm thắng Dương suy' trong bệnh lý biểu hiện như thế nào?", "opts": {"A": "Người bệnh cảm thấy nóng, sốt cao", "B": "Người bệnh cảm thấy lạnh, sợ lạnh, tay chân lạnh", "C": "Người bệnh bị xuất huyết", "D": "Người bệnh mất ngủ, bứt bối"}, "ans": "B"},
    {"q": "Hiện tượng 'Dương thắng Âm suy' trong bệnh lý biểu hiện như thế nào?", "opts": {"A": "Sợ lạnh, tay chân lạnh", "B": "Phụ nữ kinh nguyệt không đều", "C": "Nóng, sốt, khát nước, mất ngủ, bứt bối", "D": "Tiểu tiện nhiều lần"}, "ans": "C"},
    {"q": "Nguyên tắc điều trị 'Âm bệnh điều Dương, Dương bệnh điều Âm' xuất phát từ lý luận gì?", "opts": {"A": "Khí Huyết luận", "B": "Âm Dương học thuyết", "C": "Ngũ Hành học thuyết", "D": "Kinh Lạc học thuyết"}, "ans": "B"},
    {"q": "Theo Nội Kinh, sức khỏe là trạng thái gì?", "opts": {"A": "Dương luôn mạnh hơn Âm", "B": "Âm Dương cân bằng", "C": "Âm luôn mạnh hơn Dương", "D": "Khí Huyết đầy đủ"}, "ans": "B"},
    {"q": "Biến chứng 'Dương cực sinh Âm, Âm cực sinh Dương' thể hiện quy luật gì?", "opts": {"A": "Âm Dương đối lập tuyệt đối", "B": "Âm Dương có thể chuyển hóa lẫn nhau khi đạt tới cực điểm", "C": "Âm Dương luôn cân bằng", "D": "Âm Dương không liên quan đến nhau"}, "ans": "B"},
    {"q": "Màu sắc nào thuộc Dương trong phân loại Âm Dương?", "opts": {"A": "Đen, xanh đậm", "B": "Trắng, nhạt màu", "C": "Đỏ, vàng, sáng", "D": "Xanh lá cây"}, "ans": "C"},
    {"q": "Vị trí nào trên cơ thể thuộc Dương?", "opts": {"A": "Phía dưới, trong, mặt trong chi", "B": "Phía trên, ngoài, mặt ngoài chi", "C": "Lòng bàn tay, lòng bàn chân", "D": "Vùng bụng"}, "ans": "B"},
    {"q": "Vị trí nào trên cơ thể thuộc Âm?", "opts": {"A": "Lưng, đầu, mặt ngoài chi trên", "B": "Ngực, bụng, mặt trong chi", "C": "Mặt trên của cơ thể", "D": "Các vị trí nằm ngang"}, "ans": "B"},
    {"q": "Đặc tính Âm-Dương của mùa Hè là gì?", "opts": {"A": "Âm trong Dương", "B": "Dương trong Dương", "C": "Âm trong Âm", "D": "Dương trong Âm"}, "ans": "B"},
    {"q": "Đặc tính Âm-Dương của mùa Đông là gì?", "opts": {"A": "Âm trong Dương", "B": "Dương trong Âm", "C": "Âm trong Âm", "D": "Dương trong Dương"}, "ans": "C"},
    {"q": "Theo Âm Dương học thuyết, Âm hao tán sinh ra gì?", "opts": {"A": "Khí (Dương)", "B": "Tinh", "C": "Thần", "D": "Huyết"}, "ans": "A"},
    {"q": "Theo Âm Dương học thuyết, Dương hao tán sinh ra gì?", "opts": {"A": "Khí", "B": "Thần", "C": "Tinh (Âm)", "D": "Huyết"}, "ans": "C"},
    {"q": "Khái niệm 'Âm Dương giao cảm' trong Nội Kinh đề cập đến điều gì?", "opts": {"A": "Âm và Dương không thể tách rời nhau, phải tương tác", "B": "Chức năng sinh dục", "C": "Sự chuyển động của Khí", "D": "Mối quan hệ tạng phủ"}, "ans": "A"},
    {"q": "Thuốc có vị cay, nóng thì thuộc loại gì?", "opts": {"A": "Âm", "B": "Dương", "C": "Bình tính (không Âm không Dương)", "D": "Phụ thuộc liều dùng"}, "ans": "B"},
    {"q": "Thuốc có vị đắng, lạnh thì thuộc loại gì?", "opts": {"A": "Dương", "B": "Âm", "C": "Bình tính", "D": "Phụ thuộc màu sắc thuốc"}, "ans": "B"},
    {"q": "Học thuyết Âm Dương có nguồn gốc từ triết học nào của Trung Quốc cổ đại?", "opts": {"A": "Phật giáo", "B": "Khổng giáo", "C": "Đạo gia và tư duy biện chứng triển khai từ Kinh Dịch", "D": "Pháp gia"}, "ans": "C"},

    # =============================================
    # NGŨ HÀNH TƯƠNG SINH TƯƠNG KHẮC — 25 câu (26-50)
    # =============================================
    {"q": "Ngũ Hành: Mộc sinh hành nào?", "opts": {"A": "Kim", "B": "Hỏa", "C": "Thổ", "D": "Thủy"}, "ans": "B"},
    {"q": "Ngũ Hành: Hỏa sinh hành nào?", "opts": {"A": "Mộc", "B": "Kim", "C": "Thổ", "D": "Thủy"}, "ans": "C"},
    {"q": "Ngũ Hành: Thổ sinh hành nào?", "opts": {"A": "Hỏa", "B": "Mộc", "C": "Thủy", "D": "Kim"}, "ans": "D"},
    {"q": "Ngũ Hành: Kim sinh hành nào?", "opts": {"A": "Thổ", "B": "Hỏa", "C": "Thủy", "D": "Mộc"}, "ans": "C"},
    {"q": "Ngũ Hành: Thủy sinh hành nào?", "opts": {"A": "Kim", "B": "Thổ", "C": "Hỏa", "D": "Mộc"}, "ans": "D"},
    {"q": "Ngũ Hành: Mộc khắc hành nào?", "opts": {"A": "Kim", "B": "Hỏa", "C": "Thổ", "D": "Thủy"}, "ans": "C"},
    {"q": "Ngũ Hành: Hỏa khắc hành nào?", "opts": {"A": "Mộc", "B": "Thổ", "C": "Kim", "D": "Thủy"}, "ans": "C"},
    {"q": "Ngũ Hành: Thổ khắc hành nào?", "opts": {"A": "Mộc", "B": "Hỏa", "C": "Kim", "D": "Thủy"}, "ans": "D"},
    {"q": "Ngũ Hành: Kim khắc hành nào?", "opts": {"A": "Thổ", "B": "Hỏa", "C": "Thủy", "D": "Mộc"}, "ans": "D"},
    {"q": "Ngũ Hành: Thủy khắc hành nào?", "opts": {"A": "Kim", "B": "Mộc", "C": "Hỏa", "D": "Thổ"}, "ans": "C"},
    {"q": "Tạng Can (Gan) thuộc hành nào trong Ngũ Hành?", "opts": {"A": "Hỏa", "B": "Thổ", "C": "Mộc", "D": "Kim"}, "ans": "C"},
    {"q": "Tạng Tâm (Tim) thuộc hành nào trong Ngũ Hành?", "opts": {"A": "Mộc", "B": "Hỏa", "C": "Thổ", "D": "Thủy"}, "ans": "B"},
    {"q": "Tạng Tỳ (Tỳ tụy - lá) thuộc hành nào trong Ngũ Hành?", "opts": {"A": "Kim", "B": "Thủy", "C": "Hỏa", "D": "Thổ"}, "ans": "D"},
    {"q": "Tạng Phế (Phổi) thuộc hành nào trong Ngũ Hành?", "opts": {"A": "Thổ", "B": "Kim", "C": "Thủy", "D": "Mộc"}, "ans": "B"},
    {"q": "Tạng Thận (Thận) thuộc hành nào trong Ngũ Hành?", "opts": {"A": "Kim", "B": "Thổ", "C": "Mộc", "D": "Thủy"}, "ans": "D"},
    {"q": "Theo Ngũ Hành tương sinh, Can (Mộc) sinh tạng nào?", "opts": {"A": "Tỳ (Thổ)", "B": "Phế (Kim)", "C": "Tâm (Hỏa)", "D": "Thận (Thủy)"}, "ans": "C"},
    {"q": "Theo Ngũ Hành tương sinh, Tâm (Hỏa) sinh tạng nào?", "opts": {"A": "Can (Mộc)", "B": "Tỳ (Thổ)", "C": "Phế (Kim)", "D": "Thận (Thủy)"}, "ans": "B"},
    {"q": "Theo Ngũ Hành tương khắc, Can (Mộc) khắc tạng nào?", "opts": {"A": "Tâm (Hỏa)", "B": "Tỳ (Thổ)", "C": "Phế (Kim)", "D": "Thận (Thủy)"}, "ans": "B"},
    {"q": "Theo Ngũ Hành tương khắc, Tâm (Hỏa) khắc tạng nào?", "opts": {"A": "Can (Mộc)", "B": "Thận (Thủy)", "C": "Phế (Kim)", "D": "Tỳ (Thổ)"}, "ans": "C"},
    {"q": "Khi Can bệnh ảnh hưởng đến Tỳ gọi là hiện tượng gì trong Ngũ Hành?", "opts": {"A": "Tương sinh", "B": "Tương khắc (Mộc khắc Thổ)", "C": "Tự khắc", "D": "Phản khắc"}, "ans": "B"},
    {"q": "Hiện tượng 'Phản khắc' (phản bội) trong Ngũ Hành là gì?", "opts": {"A": "Hành bị khắc lại khắc ngược lại hành khắc mình, do hành bị khắc quá suy yếu", "B": "Hai hành khắc nhau cùng lúc", "C": "Tương sinh quá mạnh", "D": "Sự mất cân bằng giữa Âm và Dương"}, "ans": "A"},
    {"q": "Màu sắc nào ứng với hành Mộc (Can)?", "opts": {"A": "Đỏ", "B": "Vàng", "C": "Trắng", "D": "Xanh lá cây"}, "ans": "D"},
    {"q": "Màu sắc nào ứng với hành Hỏa (Tâm)?", "opts": {"A": "Đen", "B": "Đỏ", "C": "Xanh lá", "D": "Vàng"}, "ans": "B"},
    {"q": "Vị nào ứng với hành Thổ (Tỳ)?", "opts": {"A": "Chua", "B": "Đắng", "C": "Ngọt", "D": "Cay"}, "ans": "C"},
    {"q": "Vị nào ứng với hành Kim (Phế)?", "opts": {"A": "Mặn", "B": "Chua", "C": "Đắng", "D": "Cay"}, "ans": "D"},

    # =============================================
    # NGŨ TẠNG CHỨC NĂNG — 30 câu (51-80)
    # =============================================
    {"q": "Tạng nào chủ về Khí và hô hấp?", "opts": {"A": "Tâm", "B": "Can", "C": "Phế", "D": "Thận"}, "ans": "C"},
    {"q": "Tạng nào chủ về thần kinh (Tinh thần) và thống trị các tạng phủ khác?", "opts": {"A": "Can", "B": "Tâm", "C": "Thận", "D": "Tỳ"}, "ans": "B"},
    {"q": "Tâm khai khiếu ở đâu?", "opts": {"A": "Mắt", "B": "Mũi", "C": "Lưỡi", "D": "Tai"}, "ans": "C"},
    {"q": "Can khai khiếu ở đâu?", "opts": {"A": "Lưỡi", "B": "Mắt", "C": "Mũi", "D": "Tai"}, "ans": "B"},
    {"q": "Phế khai khiếu ở đâu?", "opts": {"A": "Mắt", "B": "Lưỡi", "C": "Tai", "D": "Mũi"}, "ans": "D"},
    {"q": "Thận khai khiếu ở đâu?", "opts": {"A": "Mũi", "B": "Mắt", "C": "Tai và Nhị âm (Tiểu tiện, Đại tiện)", "D": "Lưỡi"}, "ans": "C"},
    {"q": "Tỳ khai khiếu ở đâu?", "opts": {"A": "Mắt", "B": "Miệng (Môi)", "C": "Mũi", "D": "Lưỡi"}, "ans": "B"},
    {"q": "Tạng nào 'chủ Tinh, lưu trữ bản thể, tàng trữ Nguyên Khí'?", "opts": {"A": "Tâm", "B": "Phế", "C": "Thận", "D": "Can"}, "ans": "C"},
    {"q": "Tạng nào chủ về vận hóa và vận chuyển (hấp thu, phân phối dinh dưỡng)?", "opts": {"A": "Vị", "B": "Tỳ", "C": "Tiểu trường", "D": "Can"}, "ans": "B"},
    {"q": "Tạng nào 'chủ sơ tiết' (điều tiết sự thông suốt của Khí)?", "opts": {"A": "Tâm", "B": "Thận", "C": "Can", "D": "Phế"}, "ans": "C"},
    {"q": "Biểu hiện bệnh lý của Tâm thường gặp là gì?", "opts": {"A": "Ho, khó thở", "B": "Tim hồi hộp, mất ngủ, hay mơ, lo lắng, trí nhớ kém", "C": "Đau sườn, mắt vàng", "D": "Phụ nữ kinh nguyệt không đều"}, "ans": "B"},
    {"q": "Can chủ về 'tàng trữ Huyết', có nghĩa là gì?", "opts": {"A": "Can sản xuất ra máu", "B": "Can điều tiết lượng máu trong cơ thể, tàng trữ máu khi nghỉ ngơi", "C": "Can lọc máu sạch", "D": "Can chuyển hóa máu thành Khí"}, "ans": "B"},
    {"q": "Khi Can Khí uất kết, biểu hiện thường gặp ở đâu?", "opts": {"A": "Đau bụng dưới", "B": "Đau vùng sườn sườn (hypochondrium)", "C": "Đau vùng ngực", "D": "Đau vùng thắt lưng"}, "ans": "B"},
    {"q": "Tạng Phế chủ về 'Tuyên giáng' (phân phối Khí toàn thân), biểu hiện bệnh lý là gì?", "opts": {"A": "Phù toàn thân, tiểu tiện ít", "B": "Ho, hen, khó thở, ngực đầy", "C": "Chóng mặt, đau đầu", "D": "Ăn kém, bụng chướng"}, "ans": "B"},
    {"q": "Phế chủ về 'Thông điều Thủy đạo' (điều tiết đường nước), biểu hiện bệnh lý là gì?", "opts": {"A": "Khát nước nhiều", "B": "Tiểu nhiều", "C": "Phù, tiểu ít, cơ thể tích tụ đờm nước", "D": "Tiểu ra máu"}, "ans": "C"},
    {"q": "Thận chủ về 'Tinh', Tinh Thận gồm mấy loại?", "opts": {"A": "1 loại (Tiên thiên Tinh)", "B": "2 loại (Tiên thiên Tinh và Hậu thiên Tinh)", "C": "3 loại", "D": "4 loại"}, "ans": "B"},
    {"q": "Thận Dương (Mệnh Môn Hỏa) có chức năng chính nào?", "opts": {"A": "Lọc máu, bài tiết chất cặn", "B": "Sưu âm giữ Dương, kiềm âm, tăng âm", "C": "Ôn ấm toàn thân, thúc đẩy các hoạt động sinh lý", "D": "Tàng trữ Tinh"}, "ans": "C"},
    {"q": "Biểu hiện 'Thận Âm hư' thường gặp là gì?", "opts": {"A": "Sợ lạnh, tay chân lạnh, liệu dương", "B": "Nóng về chiều, đổ mồ hôi ban đêm (đạo hãn), hoa con (mờ mắt, bia tai)", "C": "Phù toàn thân, tiểu ít", "D": "Đau lưng, ôn ấm không đủ"}, "ans": "B"},
    {"q": "Biểu hiện 'Thận Dương hư' thường gặp là gì?", "opts": {"A": "Nóng người, bứt bối, mất ngủ", "B": "Sợ lạnh, tay chân lạnh, liệu dương, tiểu nhiều (đặc biệt ban đêm), phù", "C": "Đau sườn, mắt đỏ", "D": "Ho nhiều, đờm vàng"}, "ans": "B"},
    {"q": "Tỳ chủ về 'Thống huyết' có nghĩa là gì?", "opts": {"A": "Tỳ sản xuất ra máu", "B": "Tỳ điều khiển máu luôn luôn trong lòng mạch, tránh xuất huyết", "C": "Tỳ lọc máu", "D": "Tỳ chuyển hóa máu"}, "ans": "B"},
    {"q": "Tạng nào 'chủ bổ tinh tủy lên phổi' (thăng thanh khí)?", "opts": {"A": "Vị", "B": "Can", "C": "Tỳ", "D": "Thận"}, "ans": "C"},
    {"q": "'Phế chủ bì mao' có nghĩa gì?", "opts": {"A": "Phế điều tiết lông mày", "B": "Phế chủ về da lông, lông tơ (bì mao = da và lông)", "C": "Phế tạo ra mồ hôi", "D": "Phế làm ấm máu"}, "ans": "B"},
    {"q": "Biểu hiện bệnh lý của Tỳ Khí hư thường gặp là gì?", "opts": {"A": "Ho, khó thở, đờm nhiều", "B": "Ăn kém, bụng chướng đầy hơi, phân lỏng, mệt mỏi, mắt vàng, giảm cân", "C": "Tim hồi hộp, mất ngủ", "D": "Đau sườn, mắt đỏ"}, "ans": "B"},
    {"q": "Tạng nào 'bát kiêm' (thống trị) các tạng phủ khác theo Nội Kinh?", "opts": {"A": "Can", "B": "Phế", "C": "Tâm", "D": "Thận"}, "ans": "C"},
    {"q": "Can tàng trữ Huyết; khi ngủ thì Huyết về Can. Điều này liên quan đến chức năng gì của Can?", "opts": {"A": "Can chủ sơ tiết", "B": "Can tàng trữ và điều tiết Huyết theo nhu cầu cơ thể", "C": "Can sinh Huyết", "D": "Can lọc Huyết"}, "ans": "B"},
    {"q": "'Thận chủ xương, sinh tủy, thông não' có nghĩa là gì?", "opts": {"A": "Thận tạo ra xương mới", "B": "Tinh Thận chuyển hóa thành Tủy nuôi xương và não tủy, ảnh hưởng đến trí tuệ, xương cơ", "C": "Thận điều tiết calcium trong máu", "D": "Thận của tủy sống"}, "ans": "B"},
    {"q": "Tạng nào liên quan đến cảm xúc 'Nộ' (giận dữ)?", "opts": {"A": "Tâm", "B": "Tỳ", "C": "Can", "D": "Phế"}, "ans": "C"},
    {"q": "Tạng nào liên quan đến cảm xúc 'Bi ai' (buồn bực)?", "opts": {"A": "Thận", "B": "Tỳ", "C": "Can", "D": "Phế"}, "ans": "D"},
    {"q": "Tạng nào liên quan đến cảm xúc 'Lo sợ' (sợ hãi)?", "opts": {"A": "Can", "B": "Tâm", "C": "Thận", "D": "Phế"}, "ans": "C"},
    {"q": "'Phế chủ thanh âm' có nghĩa là gì?", "opts": {"A": "Phế tạo ra âm thanh hoạt động", "B": "Phế cung cấp Khí lực cho giọng nói, ảnh hưởng đến âm thanh tiếng nói", "C": "Phế nghe âm thanh", "D": "Phế lọc âm thanh"}, "ans": "B"},

    # =============================================
    # LỤC PHỦ CHỨC NĂNG — 20 câu (81-100)
    # =============================================
    {"q": "Lục Phủ gồm những cơ quan nào?", "opts": {"A": "Tâm, Can, Tỳ, Phế, Thận, Tâm bao", "B": "Tiểu trường, Đại trường, Vị, Đởm mật, Bàng quang, Tam tiêu", "C": "Vị, Đởm mật, Tiểu trường, Đại trường, Bàng quang, Bộ tử cung", "D": "Đởm mật, Vị, Tiểu trường, Đại trường, Bàng quang, Xương"}, "ans": "B"},
    {"q": "Chức năng chính của Vị (Dạ dày) là gì?", "opts": {"A": "Bài tiết nước tiểu", "B": "Tiếp nhận và sơ hóa thức ăn, 'Thu nạp và thục nhược' (tiếp nhận và sơ bộ phân giải)", "C": "Tẩn lọc chất cặn của trao đổi chất", "D": "Điều tiết sơ tiết Khí"}, "ans": "B"},
    {"q": "Chức năng chính của Tiểu trường là gì?", "opts": {"A": "Tàng trữ và bài tiết nước tiểu", "B": "Hấp thu dinh dưỡng, phân tách trong đục (thanh trong và chất cặn)", "C": "Sơ hóa thức ăn", "D": "Tàng trữ và bài tiết mật"}, "ans": "B"},
    {"q": "Chức năng chính của Đại trường là gì?", "opts": {"A": "Hấp thu nước từ chất cặn và bài tiết phân", "B": "Phân tách thanh đục", "C": "Sơ hóa thức ăn", "D": "Điều tiết nước tiểu"}, "ans": "A"},
    {"q": "Chức năng chính của Đởm mật (Túi mật) là gì?", "opts": {"A": "Sản xuất mật", "B": "Tàng trữ và bài tiết mật giúp tiêu hóa, 'Trung chính chi quan'", "C": "Điều tiết Khí Can", "D": "Lọc máu"}, "ans": "B"},
    {"q": "Chức năng chính của Bàng quang là gì?", "opts": {"A": "Sản xuất nước tiểu", "B": "Tàng trữ và bài tiết nước tiểu", "C": "Lọc máu", "D": "Điều tiết nước trong cơ thể"}, "ans": "B"},
    {"q": "Chức năng chính của Tam tiêu là gì?", "opts": {"A": "Tăng năng lượng cho cơ thể", "B": "Là con đường của Nguyên Khí và Thủy dịch, tham gia quản lý sự chuyển hóa Khí và Thủy", "C": "Phân giải thức ăn", "D": "Bài tiết chất cặn"}, "ans": "B"},
    {"q": "Thượng tiêu (Tam tiêu trên) liên quan đến chức năng của tạng phủ nào?", "opts": {"A": "Tỳ, Vị", "B": "Can, Đởm", "C": "Tâm, Phế", "D": "Thận, Bàng quang"}, "ans": "C"},
    {"q": "Trung tiêu (Tam tiêu giữa) liên quan đến chức năng của tạng phủ nào?", "opts": {"A": "Tâm, Phế", "B": "Tỳ, Vị", "C": "Thận, Bàng quang", "D": "Tiểu trường, Đại trường"}, "ans": "B"},
    {"q": "Hạ tiêu (Tam tiêu dưới) liên quan đến chức năng của tạng phủ nào?", "opts": {"A": "Tâm, Phế", "B": "Tỳ, Vị", "C": "Thận, Bàng quang, Tiểu trường, Đại trường", "D": "Can, Đởm"}, "ans": "C"},
    {"q": "Vị khí (Vị Khí) đi lên hay đi xuống trong trạng thái bình thường?", "opts": {"A": "Đi lên", "B": "Đi xuống", "C": "Không di chuyển", "D": "Vừa lên vừa xuống bằng nhau"}, "ans": "B"},
    {"q": "Biểu hiện 'Vị Khí nghịch lên' là gì?", "opts": {"A": "Tiểu không thông", "B": "Buồn nôn, nôn mửa, nấc, ợ, đầy bụng", "C": "Ho khan", "D": "Đau sườn"}, "ans": "B"},
    {"q": "Đởm mật kết hợp với tạng nào trong quan hệ biểu lý?", "opts": {"A": "Tâm", "B": "Phế", "C": "Can", "D": "Thận"}, "ans": "C"},
    {"q": "Bàng quang kết hợp với tạng nào trong quan hệ biểu lý?", "opts": {"A": "Phế", "B": "Tỳ", "C": "Can", "D": "Thận"}, "ans": "D"},
    {"q": "Vị kết hợp với tạng nào trong quan hệ biểu lý?", "opts": {"A": "Can", "B": "Phế", "C": "Tỳ", "D": "Tâm"}, "ans": "C"},
    {"q": "Đởm mật được gọi là gì trong Nội Kinh?", "opts": {"A": "Quan tướng chi quan (Cơ quan chuyên vận)", "B": "Trung chính chi quan (Cơ quan công bằng, quyết đoán)", "C": "Tướng quan (Cơ quan tướng lĩnh)", "D": "Quan xương (Cơ quan chặn nước)"}, "ans": "B"},
    {"q": "Khi Tiểu trường phân tách 'Thanh trọc', phần 'trong' (thanh) đi về đâu?", "opts": {"A": "Về Đại trường để thải ra ngoài", "B": "Về Tỳ để vận hóa phân phối toàn thân", "C": "Về Bàng quang để bài tiết", "D": "Về Can để tàng trữ"}, "ans": "B"},
    {"q": "Khi Tiểu trường phân tách 'Thanh trọc', phần 'đục' (chất cặn) đi về đâu?", "opts": {"A": "Về Tỳ", "B": "Về Tâm", "C": "Về Đại trường và Bàng quang", "D": "Về Can"}, "ans": "C"},
    {"q": "'Lục Phủ dư cho mà không tích' có nghĩa là gì?", "opts": {"A": "Lục Phủ cần đầy thức ăn mới hoạt động được", "B": "Lục Phủ thường thông (không nên tích trữ lâu), chức năng biểu hiện qua sự vận chuyển và bài tiết", "C": "Lục Phủ chỉ cần một ít thức ăn là đủ", "D": "Lục Phủ có khả năng tàng trữ nhiều hơn Ngũ Tạng"}, "ans": "B"},
    {"q": "Đại trường bị táo bón thường liên quan đến sự suy khí của tạng nào?", "opts": {"A": "Thận", "B": "Phế", "C": "Tâm", "D": "Can"}, "ans": "B"},

    # =============================================
    # KHÍ HUYẾT TÂN DỊCH — 20 câu (101-120)
    # =============================================
    {"q": "Khí trong Y học Cổ truyền có mấy loại chính?", "opts": {"A": "2 loại", "B": "3 loại", "C": "4 loại", "D": "5 loại"}, "ans": "C"},
    {"q": "Nguyên Khí (Yuan Qi) được tàng trữ ở đâu?", "opts": {"A": "Tâm", "B": "Phế", "C": "Thận", "D": "Tỳ"}, "ans": "C"},
    {"q": "Tông Khí (Zong Qi) được tạo ra ở đâu và chức năng là gì?", "opts": {"A": "Thận, tàng trữ bản thể", "B": "Ngực (Đan trung), kiêm trợ Phế hô hấp và Tâm tuần hoàn Huyết mạch", "C": "Vị, tiêu hóa thức ăn", "D": "Can, sơ tiết Khí"}, "ans": "B"},
    {"q": "Vinh Khí (Ying Qi) có chức năng chính là gì?", "opts": {"A": "Bảo vệ biểu phổi (mặt ngoài cơ thể)", "B": "Nuôi dưỡng toàn thân, là thành phần chính của Huyết, lưu hành trong kinh mạch", "C": "Ôn ấm cơ thể", "D": "Tàng trữ Tinh"}, "ans": "B"},
    {"q": "Vệ Khí (Wei Qi) có chức năng chính là gì?", "opts": {"A": "Nuôi dưỡng tạng phủ", "B": "Tàng trữ Nguyên Khí", "C": "Bảo vệ biểu phổi, điều tiết mồ hôi, ôn ấm cơ thể, chống ngoại tác", "D": "Chuyển hóa Hậu thiên Tinh"}, "ans": "C"},
    {"q": "Vệ Khí lưu hành ở đâu?", "opts": {"A": "Bên trong kinh mạch", "B": "Bên ngoài kinh mạch (phần biểu phổi, da, cơ)", "C": "Trong Huyết mạch", "D": "Trong tạng phủ"}, "ans": "B"},
    {"q": "Huyết (Máu) được tạo ra từ nguồn gốc nào?", "opts": {"A": "Chủ yếu từ Tiên thiên Tinh", "B": "Từ tinh tủy của thức ăn uống (Hậu thiên Tinh) với sự kiểm soát của Tâm, Tỳ, Phế, Can, Thận", "C": "Từ Tông Khí", "D": "Từ Vệ Khí"}, "ans": "B"},
    {"q": "Tạng nào 'chủ huyết' (kiểm soát sự sản xuất và lưu thông máu)?", "opts": {"A": "Can", "B": "Phế", "C": "Tâm", "D": "Thận"}, "ans": "C"},
    {"q": "Tân Dịch (chất lỏng trong cơ thể) gồm mấy loại?", "opts": {"A": "1 loại", "B": "2 loại (Tân và Dịch)", "C": "3 loại", "D": "4 loại"}, "ans": "B"},
    {"q": "'Tân' (loại chất lỏng trong) là gì?", "opts": {"A": "Chất lỏng đặc, nuôi dưỡng Tạng Phủ và xương khớp", "B": "Chất lỏng loãng, phân phối trên biểu phổi, nuôi dưỡng da cơ, điều tiết mồ hôi", "C": "Dịch não tủy", "D": "Dịch khớp xương"}, "ans": "B"},
    {"q": "'Dịch' (loại chất lỏng đặc) là gì?", "opts": {"A": "Mồ hôi", "B": "Nước mắt", "C": "Chất lỏng đặc, nuôi dưỡng não tủy, xương khớp, tạng phủ sâu", "D": "Chất lỏng loãng phân phối ở da"}, "ans": "C"},
    {"q": "Khí có chức năng 'Ôn ấm' (giữ ấm) thể hiện điều gì?", "opts": {"A": "Khí tạo ra nhiệt cho cơ thể", "B": "Khí bảo vệ khỏi lạnh", "C": "Khí duy trì nhiệt độ bình thường của cơ thể, chống lạnh", "D": "Khí làm ấm thức ăn"}, "ans": "C"},
    {"q": "Khí có chức năng 'Cố sắc' (giữ lại, không cho rỉ ra) biểu hiện như thế nào?", "opts": {"A": "Khí giữ máu trong mạch, giữ mồ hôi, giữ tinh, giữ nước tiểu", "B": "Khí đẩy thức ăn đi xuống", "C": "Khí bảo vệ cơ thể khỏi ngoại tác", "D": "Khí nuôi dưỡng tạng phủ"}, "ans": "A"},
    {"q": "Biểu hiện 'Khí hư' (thiếu Khí) thường gặp là gì?", "opts": {"A": "Nóng người, bứt bối, mất ngủ", "B": "Mệt mỏi, hay thở, thở ngắn, giọng nói nhỏ, sợ lạnh, dễ cảm lạnh", "C": "Đau sườn, bụng chướng", "D": "Tim hồi hộp, lo lắng"}, "ans": "B"},
    {"q": "Biểu hiện 'Khí trệ' (Khí bị ứ tắc) thường gặp là gì?", "opts": {"A": "Phù nhẹ, tiểu ít", "B": "Đau tức (thay đổi vị trí), bụng chướng, hơi, khó chịu toàn thân, cảm xúc không ổn định", "C": "Mệt mỏi, hay thở", "D": "Tay chân lạnh, sợ lạnh"}, "ans": "B"},
    {"q": "Nguồn gốc của Huyết (Máu) liên quan trực tiếp đến tạng phủ nào?", "opts": {"A": "Tâm và Phế", "B": "Tỳ Vị (tạo ra), Can (tàng trữ), Tâm (kiểm soát lưu thông)", "C": "Thận và Bàng quang", "D": "Can và Đởm"}, "ans": "B"},
    {"q": "Biểu hiện 'Huyết hư' (thiếu Huyết) thường gặp là gì?", "opts": {"A": "Mắt đỏ, bứt bối, mất ngủ", "B": "Mắt xanh hoặc trắng nhạt, môi nhạt, tay chân tê biệt, mất ngủ, trí nhớ kém, kinh nguyệt ít hoặc trễ", "C": "Phù, tiểu ít", "D": "Đau sườn, buồn nôn"}, "ans": "B"},
    {"q": "Khí có chức năng 'Tác động' (kích thích hoạt động sinh lý) thể hiện thế nào?", "opts": {"A": "Khí tạo ra âm thanh", "B": "Khí thúc đẩy tăng trưởng, phát triển, hoạt động sinh lý của tạng phủ và cơ thể", "C": "Khí điều tiết nhiệt độ", "D": "Khí bảo vệ biểu phổi"}, "ans": "B"},
    {"q": "Mối quan hệ giữa Khí và Huyết được tóm tắt như thế nào?", "opts": {"A": "Khí và Huyết không liên quan đến nhau", "B": "'Khí là soái của Huyết, Huyết là mẹ của Khí' — Khí thúc đẩy và kiểm soát Huyết; Huyết nuôi dưỡng và mang Khí", "C": "Huyết sản xuất ra Khí", "D": "Khí sản xuất ra Huyết"}, "ans": "B"},
    {"q": "Tân Dịch tham gia vào thành phần nào của cơ thể?", "opts": {"A": "Chỉ là nước tiểu và mồ hôi", "B": "Tham gia vào thành phần của Huyết mạch, dịch khớp, dịch não tủy, nước mắt, nước bọt, mồ hôi", "C": "Chỉ là dịch trong xương", "D": "Chỉ tham gia vào chế tạo Khí"}, "ans": "B"},

    # =============================================
    # KINH LẠC TỔNG QUAN — 20 câu (121-140)
    # =============================================
    {"q": "Hệ thống Kinh Lạc gồm bao nhiêu kinh chính (Chính kinh)?", "opts": {"A": "8 kinh", "B": "10 kinh", "C": "12 kinh", "D": "14 kinh"}, "ans": "C"},
    {"q": "12 Kinh chính được phân loại dựa theo tiêu chí nào?", "opts": {"A": "Vị trí học trên cơ thể", "B": "Tạng hay Phủ, Âm hay Dương, trên hay dưới (tay hay chân)", "C": "Chức năng chuyên biệt", "D": "Thứ tự phát hiện"}, "ans": "B"},
    {"q": "Bát Kỳ Kinh (8 kỳ kinh) khác 12 Chính kinh ở điểm nào?", "opts": {"A": "Bát Kỳ Kinh chỉ có trên tay", "B": "Bát Kỳ Kinh không trực tiếp kết nối với Tạng hoặc Phủ cụ thể nào, không có quan hệ biểu lý riêng (trừ Nhâm Đốc)", "C": "Bát Kỳ Kinh chủ về cảm xúc", "D": "Bát Kỳ Kinh ngắn hơn chính kinh"}, "ans": "B"},
    {"q": "Mạch Nhâm (Ren Mai) có đặc điểm gì?", "opts": {"A": "Chạy dọc theo lưng, chủ về Dương", "B": "Chạy dọc theo trước ngực bụng, là 'bể của các Dương kinh', chủ Âm", "C": "Chạy ngang qua ải", "D": "Chạy từ tay đến chân"}, "ans": "B"},
    {"q": "Mạch Đốc (Du Mai) có đặc điểm gì?", "opts": {"A": "Chạy ở phía trước, chủ Âm", "B": "Chạy dọc theo cột sống (lưng), là 'bể của các Âm kinh'", "C": "Chạy dọc theo cột sống (lưng), là 'bể của các Dương kinh', chủ Dương", "D": "Chạy ngang qua vùng bụng"}, "ans": "C"},
    {"q": "Vòng lưu chú của 12 Chính kinh bắt đầu từ kinh nào?", "opts": {"A": "Kinh Tâm", "B": "Kinh Phế Thủ Âm", "C": "Kinh Vị Túc Dương", "D": "Kinh Thận Túc Âm"}, "ans": "B"},
    {"q": "Sau Kinh Phế, Kinh chính nào tiếp theo trong vòng lưu chú?", "opts": {"A": "Kinh Tỳ", "B": "Kinh Đại trường", "C": "Kinh Vị", "D": "Kinh Tâm"}, "ans": "B"},
    {"q": "Kinh Thủ Âm (3 kinh Âm ở tay) gồm những kinh nào?", "opts": {"A": "Phế, Tâm, Tâm bào (Quyết tâm bào)", "B": "Phế, Tỳ, Thận", "C": "Tâm, Can, Phế", "D": "Phế, Can, Tâm bào"}, "ans": "A"},
    {"q": "Kinh Thủ Dương (3 kinh Dương ở tay) gồm những kinh nào?", "opts": {"A": "Vị, Đởm, Bàng quang", "B": "Đại trường, Tam tiêu, Tiểu trường", "C": "Tâm, Phế, Tỳ", "D": "Thận, Tâm bào, Đại trường"}, "ans": "B"},
    {"q": "Kinh Túc Dương (3 kinh Dương ở chân) gồm những kinh nào?", "opts": {"A": "Tỳ, Can, Thận", "B": "Vị, Đởm mật, Bàng quang", "C": "Đại trường, Tam tiêu, Tiểu trường", "D": "Tâm, Phế, Đại trường"}, "ans": "B"},
    {"q": "Kinh Túc Âm (3 kinh Âm ở chân) gồm những kinh nào?", "opts": {"A": "Tâm, Phế, Tâm bào", "B": "Vị, Đởm, Bàng quang", "C": "Tỳ, Can, Thận", "D": "Tiểu trường, Đại trường, Tam tiêu"}, "ans": "C"},
    {"q": "Quan hệ 'Biểu lý' giữa kinh nào?", "opts": {"A": "Phế (Âm) và Đởm (Dương)", "B": "Phế (Âm) và Đại trường (Dương)", "C": "Phế (Âm) và Tiểu trường (Dương)", "D": "Phế (Âm) và Bàng quang (Dương)"}, "ans": "B"},
    {"q": "Quan hệ 'Biểu lý' (Âm Dương phủ) giữa Tâm và cơ quan nào?", "opts": {"A": "Đại trường", "B": "Vị", "C": "Tiểu trường", "D": "Bàng quang"}, "ans": "C"},
    {"q": "Lạc mạch (Luo mai) có chức năng chính là gì?", "opts": {"A": "Điều tiết cảm xúc", "B": "Kết nối các đường kinh chính, phân phối Khí Huyết tới mọi vùng cơ thể", "C": "Tàng trữ Khí dư thừa", "D": "Bài tiết chất cặn"}, "ans": "B"},
    {"q": "Kinh biệt (Jing Bie) là gì?", "opts": {"A": "Nhánh phụ của kinh chính, đi vào sâu cơ thể kết nối với Tạng Phủ", "B": "Kinh phụ thuộc Bàng Kỳ Kinh", "C": "Đoạn kinh ở tay chân", "D": "Nhánh kinh đi ngang"}, "ans": "A"},
    {"q": "Huyệt Nguyên (Yuan points) của mỗi kinh có ý nghĩa gì?", "opts": {"A": "Điểm bắt đầu của kinh", "B": "Điểm nơi Nguyên Khí từ Thận ra biểu hiện, quan trọng trong chẩn đoán và điều trị", "C": "Điểm cuối của kinh", "D": "Điểm giao nhau của các kinh"}, "ans": "B"},
    {"q": "Khí chạy trong 12 Chính kinh theo quy luật gì?", "opts": {"A": "Tùy ý không theo quy luật", "B": "Theo giờ trong ngày (Ngọ Ký lưu chú: mỗi kinh có giờ cao điểm 2 tiếng)", "C": "Chỉ chạy ban ngày", "D": "Chỉ chạy khi ngủ"}, "ans": "B"},
    {"q": "Mạch Xung (Chong Mai) được gọi là gì?", "opts": {"A": "Bể của các Dương kinh", "B": "Bể của các Âm kinh", "C": "Bể của 12 kinh (Huyết hải)", "D": "Kinh điều tiết cảm xúc"}, "ans": "C"},
    {"q": "Hệ thống Kinh Lạc có vai trò gì trong Y học Cổ truyền?", "opts": {"A": "Chỉ sử dụng cho châm cứu", "B": "Kết nối Tạng Phủ, lưu thông Khí Huyết toàn thân, là cơ sở của châm cứu và nhiều phương pháp điều trị YHCT", "C": "Chỉ liên quan đến bệnh xương khớp", "D": "Chỉ sử dụng để chẩn đoán"}, "ans": "B"},
    {"q": "Điểm giao hội (Jiao Hui Xue) là gì?", "opts": {"A": "Điểm đầu của mỗi kinh", "B": "Điểm trên đó 2 hay nhiều đường kinh giao nhau, có thể trị nhiều chứng bệnh của nhiều kinh", "C": "Điểm cuối của kinh", "D": "Điểm đau khi ấn vào"}, "ans": "B"},

    # =============================================
    # NAN KINH ĐẶC THÙ — 20 câu (141-160)
    # =============================================
    {"q": "Nan Kinh là tác phẩm của ai, viết vào thời kỳ nào?", "opts": {"A": "Trương Trọng Cảnh, đời Hán", "B": "Biển Thước (truyền thống), thời Tây Hán hoặc sớm hơn, nội dung giải thích khó hiểu trong Nội Kinh", "C": "Hoa Đà, đời Tam Quốc", "D": "Tôn Tập, đời Đường"}, "ans": "B"},
    {"q": "Nan 1 trong Nan Kinh đề cập đến điều gì?", "opts": {"A": "Lý luận Âm Dương", "B": "Mạch Thốn Khẩu (Cun Kou) phản ánh bệnh trạng của toàn thân như thế nào", "C": "Chức năng của Ngũ Tạng", "D": "Lý luận Kinh Lạc"}, "ans": "B"},
    {"q": "Nan Kinh Nan 8 đề cập đến khái niệm gì?", "opts": {"A": "Bát Kỳ Kinh", "B": "Nguyên Khí (Yuan Qi) nằm giữa Thận và các câu hỏi về 'Thận Căn' (gốc rễ của mạng sống)", "C": "Ngũ Hành và Tạng Phủ", "D": "Khí hóa của Bàng quang"}, "ans": "B"},
    {"q": "Theo Nan Kinh, mạch 'Chân Tàng' (Zhen Cang) ở vị trí mạch nào?", "opts": {"A": "Thuộc mạch Chì (Quan)", "B": "Mạch Thốn (Cun, vị trí gần cổ tay) phản ánh trạng thái của Tạng ở phía trên", "C": "Mạch Xích (Chì, vị trí dưới) phản ánh Tạng phía dưới", "D": "Mạch Quan (giữa) phản ánh Tạng phía giữa"}, "ans": "B"},
    {"q": "Theo Nan Kinh Nan 14, 'Tổn Mạch' (mạch tổn mạc) thường xuất hiện khi nào?", "opts": {"A": "Khi người bệnh khỏe mạnh", "B": "Khi có bệnh Mạn tính nặng, Khí suy kiệt, tinh khí suy vong", "C": "Khi người bệnh bị cảm lạnh", "D": "Khi người bệnh bị stress"}, "ans": "B"},
    {"q": "Nan Kinh Nan 18 phân tích mạch theo bao nhiêu vị trí trên cổ tay?", "opts": {"A": "1 vị trí", "B": "2 vị trí", "C": "3 vị trí (Thốn, Quan, Xích)", "D": "4 vị trí"}, "ans": "C"},
    {"q": "Theo Nan Kinh, vị trí 'Thốn' (Cun) trên mạch tay phải phản ánh tạng nào?", "opts": {"A": "Can, Đởm", "B": "Thận, Bàng quang", "C": "Phế, Đại trường", "D": "Tâm, Tiểu trường"}, "ans": "C"},
    {"q": "Theo Nan Kinh, vị trí 'Xích' (Chì) trên mạch tay phải phản ánh tạng nào?", "opts": {"A": "Phế, Đại trường", "B": "Tỳ, Vị", "C": "Thận, Bàng quang và Tâm bào", "D": "Can, Đởm"}, "ans": "C"},
    {"q": "Nan Kinh Nan 25 đề cập đến 'Tam tiêu có hình hay vô hình'?", "opts": {"A": "Tam tiêu có hình, là tạng phủ cụ thể", "B": "Nan 25 đề cập đến việc Tam tiêu có tên mà không có hình (Hữu minh vô hình)", "C": "Tam tiêu là một tên khác của Tâm bào", "D": "Tam tiêu không tồn tại trong Nan Kinh"}, "ans": "B"},
    {"q": "Nan Kinh Nan 2 đề cập đến điều gì?", "opts": {"A": "Mạch xung động là âm trưởng hay dương trưởng?", "B": "Sự khác biệt giữa mạch ở vị trí Thốn và vị trí Xích", "C": "Lý luận Âm Dương cơ bản", "D": "Chức năng Ngũ Tạng"}, "ans": "B"},
    {"q": "Theo Nan Kinh, 'Tam Giao' (ba giao = Sam Jiao / Tam Tiêu) hoạt động như thế nào?", "opts": {"A": "Là cơ quan độc lập có chức năng tiêu hóa", "B": "Là cấu trúc chứa Nguyên Khí và là đường đi của Thủy dịch trong cơ thể", "C": "Là một tên khác của tử cung", "D": "Là cơ quan bài tiết"}, "ans": "B"},
    {"q": "Nan Kinh Nan 16 đề cập đến 'Ngũ Kỵ' (5 trạng thái khó trị) là gì?", "opts": {"A": "5 loại cảm xúc bệnh lý", "B": "5 trạng thái khó khăn trong chẩn đoán và tiên lượng bệnh (liệt, xuất huyết...)", "C": "5 loại khí hậu bệnh nhân", "D": "5 loại phân"}, "ans": "B"},
    {"q": "Nan Kinh bàn về bao nhiêu Nan (chương/vấn đề)?", "opts": {"A": "18 Nan", "B": "36 Nan", "C": "81 Nan", "D": "108 Nan"}, "ans": "C"},
    {"q": "Theo Nan Kinh Nan 4, Âm mạch và Dương mạch khác nhau như thế nào?", "opts": {"A": "Âm mạch chỉ chạy ban đêm, Dương mạch chỉ chạy ban ngày", "B": "Âm mạch chạy bên trong (nội), Dương mạch chạy bên ngoài (ngoại)", "C": "Âm mạch chỉ có ở tay, Dương mạch chỉ có ở chân", "D": "Không có sự khác biệt"}, "ans": "B"},
    {"q": "Nan Kinh Nan 20 đề cập đến 'Phục Mạch' là gì?", "opts": {"A": "Mạch bí ẩn (ẩn mạch), ẩn sâu không cảm rõ, biểu hiện bệnh ở bên trong", "B": "Mạch nhanh và mạnh", "C": "Mạch của người khỏe mạnh", "D": "Mạch của phụ nữ mang thai"}, "ans": "A"},
    {"q": "Theo Nan Kinh, 'Mệnh Môn' (Ming Men) ở đâu?", "opts": {"A": "Ở Tâm", "B": "Ở Thận trái", "C": "Ở khoảng giữa hai Thận, chỉ là Nguyên Khí (theo Nan 36)", "D": "Ở Tỳ"}, "ans": "C"},
    {"q": "Nan Kinh Nan 29 đề cập đến Bát Kỳ Kinh (8 kỳ kinh) có điểm gì đặc biệt?", "opts": {"A": "Bát Kỳ Kinh chỉ có 4 đường", "B": "Bát Kỳ Kinh là 'hồ' (ao chứa) của 12 chính kinh, khi 12 kinh dư thừa thì chảy vào Bát Kỳ Kinh", "C": "Bát Kỳ Kinh không có huyệt đặc hiệu", "D": "Bát Kỳ Kinh chỉ lưu hành ban đêm"}, "ans": "B"},
    {"q": "Nan Kinh Nan 27 liệt kê Bát Kỳ Kinh gồm những mạch nào?", "opts": {"A": "Đốc, Nhâm, Xung, Đới, Âm Duy, Dương Duy, Âm Kiều, Dương Kiều", "B": "Chỉ có Đốc và Nhâm", "C": "Gồm 12 kinh chính", "D": "Gồm 6 kinh Âm"}, "ans": "A"},
    {"q": "Theo Nan Kinh Nan 22, mạch 'Phục' (mạch chìm, ẩn sâu) thì bệnh ở đâu?", "opts": {"A": "Bệnh ở bên ngoài (biểu)", "B": "Bệnh ở bên trong (lý), bên trong tạng phủ", "C": "Bệnh ở kinh lạc", "D": "Không thể xác định"}, "ans": "B"},
    {"q": "Nan Kinh có giá trị gì trong YHCT?", "opts": {"A": "Chỉ có giá trị lịch sử, không áp dụng được", "B": "Là tác phẩm kinh điển giải thích Nội Kinh, mở rộng lý luận mạch học, kinh lạc, Tạng Phủ — là nền tảng của Châm cứu và Đông y truyền thống", "C": "Chỉ để tự học, không dùng làm sách giáo khoa", "D": "Chỉ liên quan đến châm cứu"}, "ans": "B"},
]

if __name__ == "__main__":
    print(f"Total questions: {len(Q0)}")
    assert len(Q0) == 160, f"Expected 160 questions, got {len(Q0)}"
    print("PASS: exactly 160 questions verified.")
